export type {
  AuthenticityEvidence,
  AuthenticityFeatureInput,
  AuthenticityMitigationWeights,
  AuthenticityResult,
  AuthenticityFeatureWeights,
  AuthenticityTagThresholds,
  CalculateScoreEngineInput,
  ConfidenceBlendWeights,
  DimensionMetricWeights,
  DimensionScoreResult,
  ExplanationContributor,
  FinalTrustResult,
  HistoricalDecayWeights,
  MetricScoreResult,
  MetricWeightDef,
  NormalizationSpec,
  NormalizationType,
  Role,
  ScoreExplanation,
  ScoreModelConfigV1,
  ScoringContext,
  ValidationResult,
} from "./types.js";
export { DIMENSION_WEIGHT_KEYS, SKILL_DIMENSIONS } from "./types.js";

/** Scoring V2 dimension model-config contracts and ScoreModel mapping. */
export {
  stableSha256,
  ModelConfigValidationError,
  SCORING_V2_DIMENSION_CONFIGS_SCHEMA_VERSION,
  createDefaultScoringV2DimensionConfigSet,
  parseScoringV2DimensionConfigSet,
  resolveScoreModelV2DimensionConfigs,
  withScoringV2DimensionConfigs,
} from "./model-config/index.js";
export type {
  ScoringV2DimensionConfigSet,
  ScoringV2DimensionConfigFingerprints,
  ResolvedScoreModelV2DimensionConfigs,
} from "./model-config/index.js";

export { clamp, clamp01, approxEqual, sum, safeDivide } from "./math.js";
export { normalizeRawValue, applyHistoricalDecay, sampleSizeConfidence } from "./normalize.js";
export { validateScoreModelConfig } from "./validate.js";
export { calculateMetricScores } from "./metrics.js";
export { calculateDimensionScores } from "./dimensions.js";
export { calculateAuthenticity } from "./authenticity.js";
export {
  gradeScore,
  presentGrade,
  calculateSkillScore,
  calculateOverallConfidence,
  calculateFinalTrust,
  resolveOverallFormula,
  buildOverallCalculationBreakdown,
} from "./trust.js";
export type { OverallScoreFormula, OverallCalculationBreakdown } from "./types.js";
export { explainScore } from "./explain.js";
export { computeInputFingerprint } from "./fingerprint.js";
export {
  createDefaultModelV1,
  createDefaultModelV2,
  createDefaultModelV3,
  createDefaultModelV4,
  createDefaultModelV5,
  createDefaultModelV6,
  createSurvivalFocusedModel,
  createUtilityFocusedModel,
  DEFAULT_V6_UTILITY_PUBLICATION_ELIGIBILITY,
} from "./model/defaults.js";
export { presentDimensionScore, presentDimensionScores } from "./present.js";
export {
  buildRankingEligibility,
  type RankingEligibilityDTO,
  type BuildRankingEligibilityInput,
} from "./ranking-eligibility.js";
export {
  buildCharacterHistoryExperienceObservations,
  type CharacterHistoryExperienceInput,
  type CharacterHistoryRunInput,
} from "./experience/character-history.js";
export {
  buildExperienceV2Observations,
  resolveExperienceProvenance,
  computeExperienceV2,
  ablateExperienceV2,
  runCalibrationPanel,
  participationDepthNormalized,
  activityRecencyNormalized,
  historicalSeasonsNormalized,
  resolvePriorSeasonSourceDepth,
  mergePriorSeasonCount,
  EXPERIENCE_V2_CALIBRATION_PANEL,
  EXPERIENCE_V2_METRIC_WEIGHTS,
  EXPERIENCE_V2_SCHEMA_VERSION,
  EXPERIENCE_V2_ANALYSIS_VERSION,
  KEY_BAND_COUNT,
  PRIOR_SEASON_RIO_DEPTH,
  PRIOR_SEASON_LOCAL_CAP,
  EXPERIENCE_KEY_BANDS,
  distinctKeyBands,
  type ExperienceV2ObservationInput,
  type ExperienceV2RunInput,
  type ExperienceHistoryProvenance,
} from "./experience/v2/index.js";
export {
  computePerformanceDimension,
  computeCurrentSeasonPeak,
  computeCurrentSeasonConsistency,
  computeHistoricalPerformance,
  resolvePerformanceMetricWeights,
  CURRENT_SEASON_PEAK_WEIGHT,
  CURRENT_SEASON_CONSISTENCY_WEIGHT,
} from "./performance/aggregate.js";
export type {
  PerformanceSummaryDTO,
  ComputePerformanceResult,
  PerformanceDungeonAggregate,
  HistoricalSeasonAggregateInput,
  PerformanceRunRefInput,
} from "./performance/types.js";
export {
  computeSurvivalDimension,
  resolveSurvivalMetricWeights,
  medianSurvivalRunScores,
  computeSurvivalConfidence,
  SURVIVAL_OUTCOME_WEIGHT,
  SURVIVAL_DEFENSIVE_RESPONSE_WEIGHT,
  SURVIVAL_EMERGENCY_RECOVERY_WEIGHT,
} from "./survival/aggregate.js";
export type {
  SurvivalSummaryDTO,
  ComputeSurvivalResult,
  ComputeSurvivalInput,
  SurvivalDungeonAggregate,
  SurvivalExplanatoryRun,
} from "./survival/types.js";
export { calculateScore, calculateScoreEngine } from "./calculate.js";
export type { CalculateScoreInput } from "./calculate.js";
export {
  validateCoherence,
  mergeObservationsWithLastKnownGood,
  buildObservationKey,
  type CoherenceValidationInput,
  type CoherenceValidationResult,
  type CoherenceViolation,
  type CoverageState,
  type PublicationStatus,
} from "./publication/coherence.js";
export {
  selectScoringRuns,
  type ScoringRunSelection,
  type ScoringRunSelectionEntry,
  type ScoringRunCandidateInput,
  type ScoringRunSelectionReason,
} from "./selection/scoring-run-selection.js";
export {
  selectSurvivalAnalysisRuns,
  type SurvivalRunSelection,
  type SurvivalRunSelectionEntry,
  type SurvivalRunCandidateInput,
  type SurvivalRunSelectionReason,
} from "./selection/survival-run-selection.js";
export {
  resolveActiveSeasonDungeonSlugs,
  resolveActiveSeasonDungeonPool,
  isDungeonInActiveSeasonPool,
  normalizeDungeonSlug,
  readBlizzardSeasonDungeonSlugsFromMetadata,
  type ResolveActiveSeasonDungeonSlugsInput,
  type ResolvedActiveSeasonDungeonPool,
  type ActiveSeasonDungeonPoolSource,
} from "./selection/active-season-dungeons.js";
export {
  toContractScoringRunSelection,
  applyRunMetadataToSelection,
  type ScoringRunPresentationMeta,
} from "./selection/scoring-run-selection-present.js";
export {
  EVIDENCE_V2_MAX_REJECTED_SUMMARIES,
  compareEvidenceCandidatesV2,
  orderEvidenceCandidatesV2,
  computeEvidenceCoverageV2,
  buildEvidenceAcquisitionPlanContentHashInput,
  computeEvidenceAcquisitionPlanContentHash,
  buildEvidenceManifestContentHashInput,
  computeEvidenceManifestContentHash,
  deepFreezeEvidenceAcquisitionPlan,
  deepFreezeEvidenceManifest,
  buildEvidenceAcquisitionPlanV2,
  finalizeEvidenceManifestV2,
  evidenceAccessStateToMissingSlot,
  type BuildEvidenceAcquisitionPlanV2Input,
  type BuildEvidenceAcquisitionPlanV2Result,
  type FinalizeEvidenceManifestV2Input,
  type FinalizeEvidenceManifestV2Result,
} from "./selection/evidence-v2-selector.js";
export {
  mythicRunToEvidenceCandidateMetadata,
  scoringRunCandidateToEvidenceMetadata,
} from "./selection/evidence-v2-adapters.js";
export {
  computeModelCoverage,
  filterPublicSkillDimensions,
  MODEL_COVERAGE_PROVISIONAL_THRESHOLD,
  type ModelCoverageSummary,
} from "./model-coverage.js";

/** Boost shadow Phase 1 — private offline extractors only (no production scoring effect). */
export {
  BOOST_FEATURE_SCHEMA_VERSION,
  BOOST_EXTRACTOR_VERSION,
  HIGH_KEY_POLICY_VERSION,
  BOOST_SHADOW_ISOLATION,
  extractBoostFeatureFactsV1,
  buildOfflineEvaluation,
  computeProgressionVelocity,
  computeTeammateScoreGap,
  computeRepeatedStrongerTeammateCohort,
  computeHighKeyGroupConcentration,
  computeVerifiedAltExperienceMitigation,
  selectHighKeySet,
  resolveCanonicalTeammateIdentity,
  resolveTimeAlignedRating,
  buildAlignedRunGaps,
  isEligibleVerifiedSubjectAtT,
  isEligibleVerifiedAltAtT,
  assertShadowOnlyFacts,
  isOmittedNotZero,
} from "./boost-shadow/index.js";
export type {
  BoostFeatureEvidenceV1,
  BoostFeatureFactsV1,
  BoostFeatureKeyV1,
  BoostFeatureMissingV1,
  BoostFeatureDiagnosticsV1,
  BoostFeatureExtractorInput,
  BoostShadowRunInput,
  BoostShadowRunParticipantInput,
  BoostShadowRatingSnapshotInput,
  VerifiedOwnershipEvidenceInput,
  BoostShadowIsolationGuarantees,
  BoostShadowOfflineEvaluationV1,
  CanonicalTeammateIdentity,
  FeatureComputeResult,
  Phase2FeatureKey,
  ResearchLabelClass,
  ResearchLabelV1,
  ProductionAuthenticityCompareV1,
  BoostShadowBacktestReportV1,
  BoostShadowBacktestArtifacts,
  BoostShadowBacktestRunOptions,
  BoostShadowExperimentParamsV1,
  BoostShadowCohortManifestV1,
  BoostShadowCohortMemberV1,
  BoostShadowOperatorInputV1,
  BoostShadowMemberEvidenceV1,
  BoostShadowEvidenceBundleV1,
  BoostShadowEvidencePort,
  MutationGuard,
  RunBoostShadowBacktestResult,
  BoostShadowFeatureRowV1,
  BoostShadowBacktestAnalysisV1,
} from "./boost-shadow/index.js";
export {
  BOOST_SHADOW_BACKTEST_REPORT_SCHEMA,
  BOOST_SHADOW_EVIDENCE_BUNDLE_SCHEMA,
  BOOST_SHADOW_COHORT_MANIFEST_SCHEMA,
  BOOST_SHADOW_EXPERIMENT_PARAMS_VERSION,
  PHASE2_FEATURE_KEYS,
  DEFAULT_BOOST_SHADOW_EXPERIMENT_PARAMS,
  mergeExperimentParams,
  validateBoostShadowCohortManifest,
  unlabeledResearchLabel,
  createMapEvidencePort,
  filterEvidenceAtCutoff,
  filterMemberEvidenceAsOf,
  filterProductionAuthenticityAsOf,
  mapPersistedCharacterSnapshotsToSeasonBound,
  emptyProductionAuthenticity,
  toExtractorInput,
  validateBoostShadowEvidenceBundle,
  assignLeakageSafeSplits,
  assertNoCharacterLeakage,
  assertNoCohortLeakage,
  computeTeammateCohortFingerprint,
  buildBacktestAnalysis,
  classifyPattern,
  experimentalUnusualPattern,
  isLabeledForSupervised,
  runBoostShadowBacktest,
  runBoostShadowBacktestFromBundle,
  createMutationGuard,
  createReadOnlyPrismaProxy,
  anonymizeBacktestReport,
  assertNoIdentityLeakage,
  buildBacktestArtifacts,
  buildPhase2FixtureBundle,
  PHASE2_FIXTURE_GENERATED_AT,
} from "./boost-shadow/index.js";
export {
  CALIBRATION_REPORT_SCHEMA_VERSION,
  COHORT_MANIFEST_SCHEMA_VERSION,
  CALIBRATION_INPUT_BUNDLE_SCHEMA_VERSION,
  validateCohortManifest,
  LABEL_RANK,
  GRADE_RANK,
  defaultBoostFlagSource,
  runCalibrationHarness,
  gradeRank,
  buildCalibrationStatistics,
  computeRankConfusion,
  detectOutliers,
  createSeededRng,
  spearmanRankCorrelation,
  averageRanksAscending,
  validateMemberEvidence,
  hasReplayableScoringContext,
  createAblatedModel,
  computeEngineWeightAblation,
  buildActiveDraftComparison,
  validateCalibrationInputBundle,
  buildCalibrationInputBundle,
  CALIBRATION_INPUT_BUNDLE_V2_SCHEMA_VERSION,
  computeCalibrationBundleV2Hash,
  validateCalibrationInputBundleV2,
  buildCalibrationInputBundleV2,
  preflightCalibrationBundleV2,
  computeArtifactSha256Hex,
  formatArtifactByteDigest,
  parseArtifactByteDigest,
  buildCalibrationContentRefV2,
  dispatchValidateCalibrationBundle,
  replayCalibrationBundleV2,
  replayCalibrationBundleV2ActiveVersusDraft,
  createMapArtifactResolverV2,
  assertDraftOnlyCreation,
  freezeDimensionModelConfigsV2,
  resolveFrozenDimensionConfigsForModel,
  strictReparseFrozenDimensionConfigs,
  CALIBRATION_REPORT_V2_SCHEMA_VERSION,
  CALIBRATION_V2_MIN_SLICE_SIZE,
  buildCalibrationReportV2Extension,
  runCalibrationHarnessFromBundle,
  runCalibrationHarnessFromExport,
  buildCalibrationArtifacts,
  reportToCsv,
  reportToJson,
  reportToMarkdown,
  anonymizeReport,
  runAdminCalibrationBacktest,
  toAdminBacktestSummary,
  buildSyntheticFixtureCohort,
  buildSyntheticFixtureBundle,
  createFixtureEvidencePort,
  V6_CANONICAL_METRIC_KEYS,
  RETIRED_PERFORMANCE_METRIC_KEYS,
  CALIBRATION_DIGEST_ALGORITHM_VERSION,
  buildCalibrationDigestV1,
  FREEZE_SNAPSHOT_SCHEMA_VERSION,
  buildDefaultFreezePolicies,
  buildFreezeSnapshot,
  computeFreezeSnapshotContentHash,
  parseAndVerifyFreezeSnapshot,
  freezeSnapshotModelToCalibrationRef,
} from "./calibration/index.js";
export type {
  CalibrationBacktestMode,
  UnsupportedCalibrationMode,
  QualitativeLabel,
  CohortMemberSource,
  CalibrationRole,
  PublicBoostFlag,
  UtilityCostSummary,
  CoverageRefreshState,
  CalibrationEvidenceCoverage,
  CalibrationMemberEvidence,
  CalibrationModelRef,
  CalibrationRunOptions,
  PerCharacterCalibrationResult,
  RankConfusionSummary,
  SliceSummary,
  DimensionSaturationSummary,
  ConfidenceCoveragePoint,
  WeightAblationResult,
  BootstrapInterval,
  CalibrationStatistics,
  CalibrationReport,
  CalibrationArtifacts,
  CalibrationInputBundleV1,
  CalibrationInputBundleV2,
  CalibrationMemberReplayV2,
  CalibrationContentRefV2,
  ArtifactDigestAlgorithmV2,
  CalibrationPreflightIssueV2,
  CalibrationBundleV2ValidationResult,
  CalibrationBundleV2PreflightResult,
  CalibrationBundleDispatchResult,
  CalibrationV2ReplayReport,
  CalibrationV2ReportExtension,
  ArtifactResolverV2,
  EvidenceValidationCode,
  EvidenceValidationIssue,
  ActiveDraftComparisonResult,
  ActiveDraftCharacterComparison,
  ActiveDraftComparisonAggregate,
  CohortManifest,
  CohortManifestMember,
  ManifestValidationResult,
  BoostFlagSource,
  CalibrationEvidencePort,
  CalibrationHarnessDeps,
  AdminBacktestSummaryV1,
  AdminCalibrationBacktestResult,
  RunAdminCalibrationBacktestInput,
  CalibrationBundleExportPort,
  BundleValidationResult,
  CalibrationDigestV1,
  DigestFinding,
  FreezeSnapshotV1,
  FreezeSnapshotMemberV1,
  FreezeSnapshotModelV1,
  FreezeSnapshotParseErrorCode,
  FreezeSnapshotParseResult,
} from "./calibration/index.js";

/** Performance V2 Phase 1 calculator (shadow — not public-activated). */
export {
  PERFORMANCE_V2_SCHEMA_VERSION,
  PERFORMANCE_V2_ALGORITHM_VERSION,
  PERFORMANCE_V2_MODEL_LABEL,
  PERFORMANCE_V2_CALIBRATION_STATUS,
  PERFORMANCE_V2_MODEL_CONFIG,
  buildDifficultyMultiplierKnots,
  interpolateDifficultyMultiplier,
  adjustParseForDifficulty,
  computeDungeonPerformance,
  computeDetailedSeasonPerformance,
  computeProfilePerformance,
  computeEqualDungeonProfilePerformance,
  computeDetailedWeight,
  blendPerformanceSources,
  computePerformanceConfidenceV2,
  resolvePerformanceRoleAdapter,
  resolveValidatedParsePercentile,
  computePerformanceV2,
  computePerformanceV2InputFingerprint,
  toPerformanceV2ShadowDimensionPayload,
  exportPerformanceV2Calibration,
  parsePerformanceV2ModelConfig,
  resolvePerformanceV2ModelConfig,
  fingerprintPerformanceV2ModelConfig,
  parsePerformanceRunParseFactV2,
  createManualDifficultyPolicyV2,
} from "./performance/v2/index.js";
export type {
  PerformanceV2CalibrationStatus,
  PerformanceV2ModelConfig,
  SeasonDifficultyPolicyV2,
  PerformanceParseSemanticV2,
  PerformanceRunParseFactV2,
  PerformanceProfileDungeonAggregateV2,
  PerformanceProfileAggregateFactV2,
  PerformanceRoleAdapterStateV2,
  PerformanceRoleAdapterResultV2,
  PerformanceAdjustedParseV2,
  PerformanceDungeonScoreV2,
  PerformanceContributorDiagnosticV2,
  PerformanceExplanationV2,
  PerformanceV2AvailabilityState,
  PerformanceV2ComputeInput,
  PerformanceV2ComputeResult,
  PerformanceV2CalibrationExport,
} from "./performance/v2/index.js";

/** Experience V3 Phase 1 calculator (shadow — not public-activated). */
export {
  EXPERIENCE_V3_SCHEMA_VERSION,
  EXPERIENCE_V3_ALGORITHM_VERSION,
  EXPERIENCE_V3_MODEL_LABEL,
  EXPERIENCE_V3_CALIBRATION_STATUS,
  EXPERIENCE_V3_COMPONENT_WEIGHTS,
  EXPERIENCE_V3_ELITE_CATALOG_VERSION,
  EXPERIENCE_V3_PREVIOUS_SEASON_POLICY_VERSION,
  EXPERIENCE_V3_HISTORICAL_RANK_POLICY_VERSION,
  EXPERIENCE_V3_MODEL_CONFIG,
  ELITE_ACHIEVEMENT_CATALOG_V1,
  getEliteCatalogEntry,
  createPreviousSeasonPolicyV3,
  createHistoricalRankPolicyV3,
  normalizePreviousSeasonScore,
  scorePreviousSeasonStrengthV3,
  scoreEliteHistoryV3,
  normalizeHistoricalRankScore,
  scoreHistoricalRankV3,
  scoreCurrentExposureV3,
  blendExperienceComponentsV3,
  computeExperienceConfidenceV3,
  computeExperienceV3,
  computeExperienceV3InputFingerprint,
  toExperienceV3ShadowDimensionPayload,
  exportExperienceV3Calibration,
  parseExperienceV3ModelConfig,
  resolveExperienceV3ModelConfig,
  fingerprintExperienceV3ModelConfig,
  EXPERIENCE_V3_DEFAULT_CONFIG_FINGERPRINT,
} from "./experience/v3/index.js";
export type {
  ExperienceV3CalibrationStatus,
  ExperienceV3ModelConfig,
  ExperienceEvidenceStateV3,
  EliteAchievementVisibilityV3,
  HistoricalRankSourceV3,
  ExperienceV3AvailabilityState,
  ExperienceV3ComponentKey,
  EliteAchievementCatalogEntryV3,
  PreviousSeasonNormalizationPolicyV3,
  HistoricalRankPolicyV3,
  ExperienceV3ExposureRunInput,
  ExperienceV3CurrentExposureFact,
  ExperienceV3PreviousSeasonFact,
  ExperienceV3EliteAchievementFact,
  ExperienceV3EliteHistoryFact,
  ExperienceV3HistoricalRankFact,
  ExperienceV3AccountBoostContract,
  ExperienceV3ComponentResult,
  ExperienceV3ContributorDiagnostic,
  ExperienceV3Explanation,
  ExperienceV3ManifestIdentity,
  ExperienceV3ComputeInput,
  ExperienceV3ComputeResult,
  ExperienceV3CalibrationExport,
} from "./experience/v3/index.js";

/** Survival V2 Phase 1 calculator (shadow — not public-activated). */
export {
  SURVIVAL_V2_SCHEMA_VERSION,
  SURVIVAL_V2_CALIBRATION_SCHEMA_VERSION,
  SURVIVAL_V2_EXTRACTOR_FAMILY,
  SURVIVAL_V2_ALGORITHM_VERSION,
  SURVIVAL_V2_MODEL_LABEL,
  SURVIVAL_V2_CALIBRATION_STATUS,
  SURVIVAL_V2_OUTCOME_BY_DEATHS,
  SURVIVAL_V2_WEIGHTS_WITH_RELATIVE,
  SURVIVAL_V2_WEIGHTS_SHADOW_OR_OFF,
  SURVIVAL_V2_DANGER,
  SURVIVAL_V2_DEFENSIVE_RATE,
  SURVIVAL_V2_METRIC_KEYS,
  SURVIVAL_V2_MODEL_CONFIG,
  parseSurvivalFactDocumentV2,
  survivalFactSlotKey,
  scoreSurvivalV2Outcome,
  scoreSurvivalV2Defensive,
  saturatingDefensiveRateScore,
  mergePressureClusters,
  scoreSurvivalV2EmergencyRecovery,
  scoreSurvivalV2RelativeDamageShadow,
  isSurvivalV2RelativeDamageWeightActive,
  relativeDamageBlendScore,
  resolveSurvivalV2Weights,
  scoreSurvivalV2Run,
  medianOf,
  meanOf,
  aggregateSurvivalV2Dungeon,
  aggregateSurvivalV2Season,
  computeSurvivalV2Confidence,
  computeSurvivalV2,
  buildSurvivalV2InputFingerprint,
  toSurvivalV2ShadowDimensionPayload,
  exportSurvivalV2Calibration,
  parseSurvivalV2ModelConfig,
  resolveSurvivalV2ModelConfig,
  fingerprintSurvivalV2ModelConfig,
} from "./survival/v2/index.js";
export type {
  SurvivalV2RelativeDamageMode,
  SurvivalV2CalibrationStatus,
  SurvivalV2ModelConfig,
  SurvivalFactDocumentV2,
  SurvivalV2AvailabilityState,
  SurvivalV2CalibrationExport,
  SurvivalV2ComputeInput,
  SurvivalV2ComputeResult,
  SurvivalV2ComponentResult,
  SurvivalV2ContributorDiagnostic,
  SurvivalV2DangerWindowFact,
  SurvivalV2DungeonAggregate,
  SurvivalV2HealthEvidenceMode,
  SurvivalV2RelativeDamageShadow,
  SurvivalV2RunScore,
  SurvivalV2ShadowDimensionPayload,
  SurvivalV2ToolkitAvailabilityState,
  SurvivalV2ToolkitEntry,
} from "./survival/v2/index.js";

/** Utility V2 Phase 1 calculator (shadow — not public-activated). */
export {
  UTILITY_V2_SCHEMA_VERSION,
  UTILITY_V2_EXTRACTOR_FAMILY,
  UTILITY_V2_EXTRACTOR_VERSION,
  UTILITY_V2_ALGORITHM_VERSION,
  UTILITY_V2_MODEL_LABEL,
  UTILITY_V2_CALIBRATION_STATUS,
  UTILITY_V2_DOMAIN_WEIGHTS,
  UTILITY_V2_DOMAIN_CONTRIBUTION_CAP,
  UTILITY_V2_SCORE_FLOOR,
  UTILITY_V2_INTERRUPT_CREDITS,
  UTILITY_V2_UNMATCHED_CREDIT_SHARE_CAP,
  UTILITY_V2_UNMATCHED_ONLY_MAX_DOMAIN_SCORE,
  UTILITY_V2_SUPPORT_SEMANTIC_CREDIT,
  UTILITY_V2_SCORE_SEMANTICS,
  UTILITY_V2_MODEL_CONFIG,
  classifyInterruptAttempts,
  sumInterruptCredits,
  estimateActiveCombatMs,
  activeCombatHours,
  bindUtilityV2FactsToManifest,
  selectedManifestSlots,
  computeUtilityV2InputFingerprint,
  stableStringify,
  computeUtilityV2,
  applyUnmatchedSpamCap,
  dedupeStrategicCc,
  scoreSupportCredit,
  emptyUtilityV2FactSet,
  toUtilityV2ShadowDimensionPayload,
  exportUtilityV2Calibration,
  buildUtilityV2RunFactSet,
  parseUtilityV2ModelConfig,
  resolveUtilityV2ModelConfig,
  fingerprintUtilityV2ModelConfig,
  UTILITY_V2_DEFAULT_CONFIG_FINGERPRINT,
} from "./utility/v2/index.js";
export type {
  UtilityV2DomainKey,
  UtilityV2SupportSemantic,
  UtilityV2CalibrationStatus,
  UtilityV2ModelConfig,
  ClassifyInterruptAttemptsInput,
  ActiveCombatEstimate,
  InterruptAttemptClass,
  UtilityV2ActorKind,
  UtilityV2AvailabilityState,
  UtilityV2FrozenSlotIdentity,
  UtilityV2ManifestSlotRef,
  UtilityV2FrozenManifestRef,
  UtilityV2InterruptAttemptSeed,
  UtilityV2ConfirmedInterruptEvent,
  UtilityV2HostileCastWindow,
  ClassifiedInterruptAttempt,
  UtilityV2CcAction,
  UtilityV2SupportAction,
  UtilityV2ToolkitApplicability,
  UtilityV2RunFactSet,
  UtilityV2DomainBreakdown,
  UtilityV2InterruptCounts,
  UtilityV2ComputeInput,
  UtilityV2ComputeResult,
  UtilityV2Explanation,
  UtilityV2BindingResult,
  UtilityV2ShadowDimensionPayload,
  UtilityV2ShadowDimensionRecord,
  UtilityV2CalibrationExport,
  BuildUtilityV2FactSetInput,
} from "./utility/v2/index.js";

/** Scoring V2 explainability builders (WS11). */
export {
  buildExplainabilityV2Admin,
  toPublicExplainabilityV2,
  buildExplainabilityV2Public,
  derivePublicationState,
  isPubliclyEmittablePublicationState,
  sortPublicContributors,
} from "./explainability-v2/index.js";
export type {
  BuildExplainabilityV2AdminInput,
  ExplainabilityV2BatchSource,
  ExplainabilityV2DatasetSource,
  ExplainabilityV2DimensionSource,
  ExplainabilityV2FactSetSource,
  ExplainabilityV2RejectedSource,
  ExplainabilityV2SlotSource,
  ExplainabilityV2V1SnapshotSource,
} from "./explainability-v2/index.js";

/** Shared Shadow DimensionComputation normalization (WS10). */
export {
  DIMENSION_COMPUTATION_LIFECYCLE_SHADOW,
  normalizeShadowDimensionRecord,
  buildUnavailableShadowDimensionRecord,
  availabilityFromComputeState,
  availabilityFromUtilityResult,
  isShadowPlaceholderFact,
  limitationsFromFact,
  validateFrozenManifestIdentities,
  verifyManifestContentHash,
  verifyFactSetHashesAgainstManifest,
  buildUnavailableInputFingerprint,
  algorithmVersionForDimension,
  adaptPerformanceComputeInput,
  adaptSurvivalComputeInput,
  adaptUtilityComputeInput,
  adaptExperienceComputeInput,
  finalizeShadowDimensions,
  buildSlotFactSetBindingHash,
} from "./dimensions/v2/index.js";
export type {
  ScoringV2PublicDimension,
  DimensionComputationLifecycleState,
  DimensionAvailabilityState,
  NormalizedShadowDimensionMetrics,
  NormalizedShadowDimensionRecord,
  ShadowDimensionPayloadLike,
  NormalizeShadowDimensionRecordInput,
  BuildUnavailableShadowDimensionRecordInput,
  PersistedFactSetRef,
  FrozenSlotIdentityIssue,
  FactReadinessResult,
  PerformanceAdapterResult,
  SurvivalAdapterResult,
  UtilityAdapterResult,
  ExperienceAdapterResult,
  ExperienceHistoryInputs,
  ShadowDimensionFinalizerOutcomeStatus,
  ShadowDimensionFinalizerOutcome,
  FinalizeShadowDimensionsInput,
  FinalizeShadowDimensionsResult,
} from "./dimensions/v2/index.js";
