-- Optional concurrent character-search indexes (non-transactional ops only).
-- CREATE INDEX CONCURRENTLY cannot run inside Prisma migrate deploy transactions.
--
-- pg_trgm + GIN on name_search_key are now applied by Prisma migration
-- 20260731180000_character_name_search_trgm (transactional CREATE INDEX).
-- Do not recreate that index here unless recovering a database that skipped migrate.
--
-- The btree on name_search_key remains from 20260731140000_character_name_search_key.

-- CREATE INDEX CONCURRENTLY IF NOT EXISTS characters_normalized_name_trgm
--   ON characters USING gin (normalized_name gin_trgm_ops);
