/**
 * Stable structured log event names for Wave 3 refresh / provider / scoring observability.
 * Prefer these over free-form messages so operators can filter and correlate reliably.
 */
export const OBS_EVENTS = {
  refreshRequested: "refresh.requested",
  refreshDedupe: "refresh.dedupe",
  refreshEnqueueOk: "refresh.enqueue.success",
  refreshEnqueueFail: "refresh.enqueue.failure",
  refreshWorkerStarted: "refresh.worker.started",
  refreshProviderPhaseStarted: "refresh.provider.phase.started",
  refreshProviderPhaseCompleted: "refresh.provider.phase.completed",
  refreshFusionCompleted: "refresh.fusion.completed",
  refreshScoreCalculated: "refresh.score.calculated",
  refreshPersistenceCompleted: "refresh.persistence.completed",
  refreshTerminal: "refresh.terminal",
  providerOperation: "provider.operation",
  refreshAdmissionShadow: "refresh.admission.shadow",
  refreshAdmissionReserved: "refresh.admission.reserved",
  refreshAdmissionDeferred: "refresh.admission.deferred",
  refreshAdmissionDenied: "refresh.admission.denied",
  refreshAdmissionSettled: "refresh.admission.settled",
  refreshLeaseRenewed: "refresh.lease.renewed",
  refreshLeaseExpired: "refresh.lease.expired",
  refreshSlotAcquired: "refresh.slot.acquired",
  refreshSlotReleased: "refresh.slot.released",

  // Scoring V2 lifecycle (normative names from 15_TESTING_VALIDATION_OBSERVABILITY.md)
  scoringV2DiscoveryStarted: "scoring_v2.discovery_started",
  scoringV2DiscoveryCompleted: "scoring_v2.discovery_completed",
  scoringV2ManifestFrozen: "scoring_v2.manifest_frozen",
  scoringV2AdmissionAdmitted: "scoring_v2.admission_admitted",
  scoringV2AdmissionDeferred: "scoring_v2.admission_deferred",
  scoringV2AdmissionStopped: "scoring_v2.admission_stopped",
  scoringV2SlotStarted: "scoring_v2.slot_started",
  scoringV2SlotCompleted: "scoring_v2.slot_completed",
  scoringV2SlotFailed: "scoring_v2.slot_failed",
  scoringV2DatasetCacheHit: "scoring_v2.dataset_cache_hit",
  scoringV2DatasetFetched: "scoring_v2.dataset_fetched",
  scoringV2DatasetTruncated: "scoring_v2.dataset_truncated",
  scoringV2FactSetWritten: "scoring_v2.fact_set_written",
  scoringV2BatchReady: "scoring_v2.batch_ready",
  scoringV2BatchFinalized: "scoring_v2.batch_finalized",
  scoringV2PublicationCandidate: "scoring_v2.publication_candidate",
  scoringV2PublicationPublished: "scoring_v2.publication_published",
  scoringV2PublicationRejected: "scoring_v2.publication_rejected",
  scoringV2CalibrationStarted: "scoring_v2.calibration_started",
  scoringV2CalibrationCompleted: "scoring_v2.calibration_completed",
  scoringV2ReferenceSliceStateChanged: "scoring_v2.reference_slice_state_changed",
  // Admin control center (bounded; no PII / secrets)
  scoringV2AdminEvidenceExportRequested: "scoring_v2.admin_evidence_export_requested",
  scoringV2AdminEvidenceExportStarted: "scoring_v2.admin_evidence_export_started",
  scoringV2AdminEvidenceExportCompleted: "scoring_v2.admin_evidence_export_completed",
  scoringV2AdminEvidenceExportFailed: "scoring_v2.admin_evidence_export_failed",
  scoringV2AdminBundleFrozen: "scoring_v2.admin_bundle_frozen",
  scoringV2AdminConcurrencyUpdated: "scoring_v2.admin_concurrency_updated",
  scoringV2ConcurrencyPermitAcquired: "scoring_v2.concurrency_permit_acquired",
  scoringV2ConcurrencyPermitReleased: "scoring_v2.concurrency_permit_released",
  scoringV2ConcurrencyLimitReached: "scoring_v2.concurrency_limit_reached",
  // Finalization recovery (operational; complements normative batch lifecycle)
  scoringV2FinalizationClaimReleased: "scoring_v2.finalization_claim_released",
  scoringV2FinalizationClaimLost: "scoring_v2.finalization_claim_lost",
  scoringV2FinalizationReclaim: "scoring_v2.finalization_reclaim",
} as const;

export type ObsEventName = (typeof OBS_EVENTS)[keyof typeof OBS_EVENTS];
