/**
 * Stable structured log event names for Wave 3 refresh / provider / scoring observability.
 * Prefer these over free-form messages so operators can filter and correlate reliably.
 */
export const OBS_EVENTS = {
  refreshRequested: "refresh.requested",
  refreshDedupe: "refresh.dedupe",
  refreshEnqueueOk: "refresh.enqueue.success",
  refreshEnqueueFail: "refresh.enqueue.failure",
  refreshWorkerStarted: "refresh.worker.started",
  refreshProviderPhaseStarted: "refresh.provider.phase.started",
  refreshProviderPhaseCompleted: "refresh.provider.phase.completed",
  refreshFusionCompleted: "refresh.fusion.completed",
  refreshScoreCalculated: "refresh.score.calculated",
  refreshPersistenceCompleted: "refresh.persistence.completed",
  refreshTerminal: "refresh.terminal",
  providerOperation: "provider.operation",
  refreshAdmissionShadow: "refresh.admission.shadow",
  refreshAdmissionReserved: "refresh.admission.reserved",
  refreshAdmissionDeferred: "refresh.admission.deferred",
  refreshAdmissionDenied: "refresh.admission.denied",
  refreshAdmissionSettled: "refresh.admission.settled",
  refreshLeaseRenewed: "refresh.lease.renewed",
  refreshLeaseExpired: "refresh.lease.expired",
  refreshSlotAcquired: "refresh.slot.acquired",
  refreshSlotReleased: "refresh.slot.released",

  // Scoring V2 lifecycle (normative names from 15_TESTING_VALIDATION_OBSERVABILITY.md)
  scoringDiscoveryStarted: "scoring.discovery_started",
  scoringDiscoveryCompleted: "scoring.discovery_completed",
  scoringManifestFrozen: "scoring.manifest_frozen",
  scoringAdmissionAdmitted: "scoring.admission_admitted",
  scoringAdmissionDeferred: "scoring.admission_deferred",
  scoringAdmissionStopped: "scoring.admission_stopped",
  scoringSlotStarted: "scoring.slot_started",
  scoringSlotCompleted: "scoring.slot_completed",
  scoringSlotFailed: "scoring.slot_failed",
  scoringDatasetCacheHit: "scoring.dataset_cache_hit",
  scoringDatasetFetched: "scoring.dataset_fetched",
  scoringDatasetTruncated: "scoring.dataset_truncated",
  scoringFactSetWritten: "scoring.fact_set_written",
  scoringBatchReady: "scoring.batch_ready",
  scoringBatchFinalized: "scoring.batch_finalized",
  scoringPublicationCandidate: "scoring.publication_candidate",
  scoringPublicationPublished: "scoring.publication_published",
  scoringPublicationRejected: "scoring.publication_rejected",
  scoringCalibrationStarted: "scoring.calibration_started",
  scoringCalibrationCompleted: "scoring.calibration_completed",
  scoringReferenceSliceStateChanged: "scoring.reference_slice_state_changed",
  // Admin control center (bounded; no PII / secrets)
  scoringAdminEvidenceExportRequested: "scoring.admin_evidence_export_requested",
  scoringAdminEvidenceExportStarted: "scoring.admin_evidence_export_started",
  scoringAdminEvidenceExportCompleted: "scoring.admin_evidence_export_completed",
  scoringAdminEvidenceExportFailed: "scoring.admin_evidence_export_failed",
  scoringAdminBundleFrozen: "scoring.admin_bundle_frozen",
  scoringAdminConcurrencyUpdated: "scoring.admin_concurrency_updated",
  scoringConcurrencyPermitAcquired: "scoring.concurrency_permit_acquired",
  scoringConcurrencyPermitReleased: "scoring.concurrency_permit_released",
  scoringConcurrencyLimitReached: "scoring.concurrency_limit_reached",
  // Finalization recovery (operational; complements normative batch lifecycle)
  scoringFinalizationClaimReleased: "scoring.finalization_claim_released",
  scoringFinalizationClaimLost: "scoring.finalization_claim_lost",
  scoringFinalizationReclaim: "scoring.finalization_reclaim",
} as const;

export type ObsEventName = (typeof OBS_EVENTS)[keyof typeof OBS_EVENTS];
