import type { MechanicCatalog } from "./types.js";

/** Minimal illustrative seed — empty rules are production-safe; this aids matcher tests. */
export const MINIMAL_SEED_CATALOG: MechanicCatalog = {
  catalogVersion: "0.1.0-seed",
  seasonSlug: "placeholder-current",
  rules: [
    {
      id: "seed-avoidable-1",
      seasonSlug: "placeholder-current",
      dungeonSlug: "example-dungeon",
      npcId: 100001,
      spellId: 400001,
      ruleType: "AVOIDABLE_DAMAGE",
      severity: 2,
      applicableRoles: ["DPS", "TANK", "HEALER"],
      responseSpellIds: [],
      notes: "Synthetic avoidable ground effect for fixtures",
      source: "seed",
      version: "0.1.0",
      active: true,
    },
    {
      id: "seed-mandatory-1",
      seasonSlug: "placeholder-current",
      dungeonSlug: "example-dungeon",
      npcId: 100002,
      spellId: 400002,
      ruleType: "MANDATORY_DAMAGE",
      severity: 1,
      applicableRoles: ["DPS", "TANK", "HEALER"],
      responseSpellIds: [],
      notes: "Synthetic mandatory tank buster",
      source: "seed",
      version: "0.1.0",
      active: true,
    },
    {
      id: "seed-soak-1",
      seasonSlug: "placeholder-current",
      dungeonSlug: "example-dungeon",
      npcId: null,
      spellId: 400003,
      ruleType: "SOAK",
      severity: 1,
      applicableRoles: ["DPS", "TANK", "HEALER"],
      responseSpellIds: [],
      notes: "Synthetic soak mechanic",
      source: "seed",
      version: "0.1.0",
      active: true,
    },
    {
      id: "seed-interrupt-1",
      seasonSlug: "placeholder-current",
      dungeonSlug: "example-dungeon",
      npcId: 100003,
      spellId: 400010,
      ruleType: "PRIORITY_INTERRUPT",
      severity: 3,
      applicableRoles: ["DPS", "TANK", "HEALER"],
      responseSpellIds: [],
      notes: "Synthetic priority cast",
      source: "seed",
      version: "0.1.0",
      active: true,
    },
  ],
};
