import type { AbilityRule } from "../../types.js";
import { ALL_ROLES, DPS, TANK, TANK_DPS, rule, performanceCooldownRule } from "../rule.js";

/** Death Knight survival / utility catalog (Retail M+). */
export const DEATH_KNIGHT_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "death-knight.interrupt.mind-freeze",
    name: "Mind Freeze",
    spellIds: [47528],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "INTERRUPT",
    cooldownSeconds: 15,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "death-knight.hard-cc.asphyxiate",
    name: "Asphyxiate",
    spellIds: [221562],
    classSlug: "death-knight",
    roles: TANK_DPS,
    category: "HARD_CC",
    availability: "TALENT",
    cooldownSeconds: 45,
  }),
  rule({
    canonicalKey: "death-knight.soft-cc.blinding-sleet",
    name: "Blinding Sleet",
    spellIds: [207167],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "death-knight.soft-cc.death-grip",
    name: "Death Grip",
    spellIds: [49576],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "SOFT_CC",
    cooldownSeconds: 25,
  }),
  rule({
    canonicalKey: "death-knight.soft-cc.control-undead",
    name: "Control Undead",
    spellIds: [111673],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "SOFT_CC",
  }),
  rule({
    canonicalKey: "death-knight.defensive-major.anti-magic-shell",
    name: "Anti-Magic Shell",
    spellIds: [48707],
    activationSpellIds: [48707],
    activationBuffIds: [48707],
    triggeredEffectIds: [444741],
    activationSource: "PLAYER_CAST",
    activationEventTypes: ["cast"],
    activationEffectDurationMs: 8_000,
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MAJOR",
    cooldownSeconds: 60,
    notes:
      "Canonical cast/aura 48707. 444741 is the Midnight AMS absorb/pet aura effect — " +
      "correlation evidence only (not an activation-opening alias).",
  }),
  rule({
    canonicalKey: "death-knight.defensive-major.icebound-fortitude",
    name: "Icebound Fortitude",
    spellIds: [48792],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MAJOR",
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "death-knight.defensive-major.vampiric-blood",
    name: "Vampiric Blood",
    spellIds: [55233],
    classSlug: "death-knight",
    specSlugs: ["blood"],
    roles: TANK,
    category: "DEFENSIVE_MAJOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 90,
  }),
  rule({
    canonicalKey: "death-knight.defensive-minor.rune-tap",
    name: "Rune Tap",
    spellIds: [194679],
    classSlug: "death-knight",
    specSlugs: ["blood"],
    roles: TANK,
    category: "DEFENSIVE_MINOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 25,
  }),
  rule({
    canonicalKey: "death-knight.immunity.lichborne",
    name: "Lichborne",
    spellIds: [49039],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "IMMUNITY",
    availability: "TALENT",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "death-knight.self-heal.death-strike",
    name: "Death Strike",
    spellIds: [49998],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "SELF_HEAL",
  }),
  rule({
    canonicalKey: "death-knight.self-heal.death-pact",
    name: "Death Pact",
    spellIds: [48743],
    classSlug: "death-knight",
    roles: TANK_DPS,
    category: "SELF_HEAL",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "death-knight.group-utility.anti-magic-zone",
    name: "Anti-Magic Zone",
    spellIds: [51052],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    availability: "TALENT",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "death-knight.battle-rez.raise-ally",
    name: "Raise Ally",
    spellIds: [61999],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "BATTLE_REZ",
    cooldownSeconds: 600,
  }),

  // Performance offensive cooldowns (canonical AbilityRule entries).
    performanceCooldownRule({
      canonicalKey: "death-knight.offensive.dancing-rune-weapon",
      name: "Dancing Rune Weapon",
      spellIds: [49028],
      activationBuffIds: [81256],
      classSlug: "death-knight",
      specSlugs: ["blood"],
      roles: TANK,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 120,
      notes: "Blood major offensive + defensive hybrid; retained as Performance CD.",
    }),
    performanceCooldownRule({
      canonicalKey: "death-knight.offensive.abomination-limb",
      name: "Abomination Limb",
      spellIds: [383269],
      activationSpellIds: [383269],
      classSlug: "death-knight",
      roles: [...TANK, ...DPS],
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 120,
      activationSource: "PLAYER_CAST",
      activationEventTypes: ["cast"],
      // WCL emits repeated cast ticks of 383269 during the limb window (~1–4s apart;
      // observed clusters span up to ~27s). Only the first cast opens an activation.
      activationEffectDurationMs: 30_000,
      notes:
        "Class talent offensive grip/damage window. Same-spell Casts ticks during the effect are correlated, not new uses.",
    }),
    performanceCooldownRule({
      canonicalKey: "death-knight.offensive.bonestorm",
      name: "Bonestorm",
      spellIds: [194844],
      classSlug: "death-knight",
      specSlugs: ["blood"],
      roles: TANK,
      category: "OFFENSIVE_MINOR",
      availability: "TALENT",
      cooldownSeconds: 60,
    }),
    performanceCooldownRule({
      canonicalKey: "death-knight.offensive.pillar-of-frost",
      name: "Pillar of Frost",
      spellIds: [51271],
      activationBuffIds: [51271],
      classSlug: "death-knight",
      specSlugs: ["frost"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 60,
    }),
    performanceCooldownRule({
      canonicalKey: "death-knight.offensive.empower-rune-weapon",
      name: "Empower Rune Weapon",
      spellIds: [47568],
      classSlug: "death-knight",
      specSlugs: ["frost"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 120,
    }),
    performanceCooldownRule({
      canonicalKey: "death-knight.offensive.breath-of-sindragosa",
      name: "Breath of Sindragosa",
      spellIds: [152279],
      activationBuffIds: [152279],
      classSlug: "death-knight",
      specSlugs: ["frost"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 120,
    }),
    performanceCooldownRule({
      canonicalKey: "death-knight.offensive.frostwyrms-fury",
      name: "Frostwyrm's Fury",
      spellIds: [279302],
      classSlug: "death-knight",
      specSlugs: ["frost"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 90,
    }),
    performanceCooldownRule({
      canonicalKey: "death-knight.offensive.army-of-the-dead",
      name: "Army of the Dead",
      spellIds: [42650],
      activationSpellIds: [42650],
      activationBuffIds: [42650],
      classSlug: "death-knight",
      specSlugs: ["unholy"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 90,
      activationSource: "PLAYER_CAST",
      activationEventTypes: ["cast", "applybuff"],
      notes:
        "Major Unholy summon window; cast-primary (applybuff correlates). Catalog CD 90s from observed ~90s cast gaps (legacy 180s reduced by current talents/patch).",
    }),
    performanceCooldownRule({
      canonicalKey: "death-knight.offensive.apocalypse",
      name: "Apocalypse",
      spellIds: [275699],
      classSlug: "death-knight",
      specSlugs: ["unholy"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 90,
    }),
    performanceCooldownRule({
      canonicalKey: "death-knight.offensive.dark-transformation",
      name: "Dark Transformation",
      spellIds: [63560],
      activationBuffIds: [63560],
      classSlug: "death-knight",
      specSlugs: ["unholy"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 60,
      sourceOwnership: "ANY_OWNED",
    }),
    performanceCooldownRule({
      canonicalKey: "death-knight.offensive.unholy-assault",
      name: "Unholy Assault",
      spellIds: [207289],
      activationBuffIds: [207289],
      classSlug: "death-knight",
      specSlugs: ["unholy"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 90,
    }),
    performanceCooldownRule({
      canonicalKey: "death-knight.offensive.summon-gargoyle",
      name: "Summon Gargoyle",
      spellIds: [49206],
      aliases: [207349],
      classSlug: "death-knight",
      specSlugs: ["unholy"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 180,
      notes: "Includes Dark Arbiter talent replacement alias when observed.",
    }),
];
