import type { AbilityRule } from "../../types.js";
import { ALL_ROLES, TANK, TANK_DPS, rule } from "../rule.js";

/** Death Knight survival / utility catalog (Retail M+). */
export const DEATH_KNIGHT_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "death-knight.interrupt.mind-freeze",
    name: "Mind Freeze",
    spellIds: [47528],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "INTERRUPT",
    cooldownSeconds: 15,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "death-knight.hard-cc.asphyxiate",
    name: "Asphyxiate",
    spellIds: [221562],
    classSlug: "death-knight",
    roles: TANK_DPS,
    category: "HARD_CC",
    availability: "TALENT",
    cooldownSeconds: 45,
  }),
  rule({
    canonicalKey: "death-knight.soft-cc.blinding-sleet",
    name: "Blinding Sleet",
    spellIds: [207167],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "death-knight.soft-cc.death-grip",
    name: "Death Grip",
    spellIds: [49576],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "SOFT_CC",
    cooldownSeconds: 25,
  }),
  rule({
    canonicalKey: "death-knight.soft-cc.control-undead",
    name: "Control Undead",
    spellIds: [111673],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "SOFT_CC",
  }),
  rule({
    canonicalKey: "death-knight.defensive-major.anti-magic-shell",
    name: "Anti-Magic Shell",
    spellIds: [48707],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MAJOR",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "death-knight.defensive-major.icebound-fortitude",
    name: "Icebound Fortitude",
    spellIds: [48792],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MAJOR",
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "death-knight.defensive-major.vampiric-blood",
    name: "Vampiric Blood",
    spellIds: [55233],
    classSlug: "death-knight",
    specSlugs: ["blood"],
    roles: TANK,
    category: "DEFENSIVE_MAJOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 90,
  }),
  rule({
    canonicalKey: "death-knight.defensive-minor.rune-tap",
    name: "Rune Tap",
    spellIds: [194679],
    classSlug: "death-knight",
    specSlugs: ["blood"],
    roles: TANK,
    category: "DEFENSIVE_MINOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 25,
  }),
  rule({
    canonicalKey: "death-knight.immunity.lichborne",
    name: "Lichborne",
    spellIds: [49039],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "IMMUNITY",
    availability: "TALENT",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "death-knight.self-heal.death-strike",
    name: "Death Strike",
    spellIds: [49998],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "SELF_HEAL",
  }),
  rule({
    canonicalKey: "death-knight.self-heal.death-pact",
    name: "Death Pact",
    spellIds: [48743],
    classSlug: "death-knight",
    roles: TANK_DPS,
    category: "SELF_HEAL",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "death-knight.group-utility.anti-magic-zone",
    name: "Anti-Magic Zone",
    spellIds: [51052],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    availability: "TALENT",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "death-knight.battle-rez.raise-ally",
    name: "Raise Ally",
    spellIds: [61999],
    classSlug: "death-knight",
    roles: ALL_ROLES,
    category: "BATTLE_REZ",
    cooldownSeconds: 600,
  }),
];
