import type { AbilityRule } from "../../types.js";
import { ALL_ROLES, DPS, TANK, TANK_DPS, rule } from "../rule.js";

/**
 * Demon Hunter survival / utility catalog (Retail M+).
 * Devourer inherits class-shared utilities only; spec-specific toolkit not cataloged.
 */
export const DEMON_HUNTER_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "demon-hunter.interrupt.disrupt",
    name: "Disrupt",
    spellIds: [183752],
    classSlug: "demon-hunter",
    roles: ALL_ROLES,
    category: "INTERRUPT",
    cooldownSeconds: 15,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "demon-hunter.hard-cc.imprison",
    name: "Imprison",
    spellIds: [217832],
    classSlug: "demon-hunter",
    roles: ALL_ROLES,
    category: "HARD_CC",
    cooldownSeconds: 45,
  }),
  rule({
    canonicalKey: "demon-hunter.hard-cc.chaos-nova",
    name: "Chaos Nova",
    spellIds: [179057],
    classSlug: "demon-hunter",
    roles: ALL_ROLES,
    category: "HARD_CC",
    cooldownSeconds: 45,
  }),
  rule({
    canonicalKey: "demon-hunter.hard-cc.fel-eruption",
    name: "Fel Eruption",
    spellIds: [211881],
    classSlug: "demon-hunter",
    roles: ALL_ROLES,
    category: "HARD_CC",
    availability: "TALENT",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "demon-hunter.hard-cc.sigil-of-misery",
    name: "Sigil of Misery",
    spellIds: [207684],
    classSlug: "demon-hunter",
    roles: ALL_ROLES,
    category: "HARD_CC",
    availability: "TALENT",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "demon-hunter.soft-cc.sigil-of-silence",
    name: "Sigil of Silence",
    spellIds: [202137],
    classSlug: "demon-hunter",
    roles: ALL_ROLES,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "demon-hunter.soft-cc.sigil-of-chains",
    name: "Sigil of Chains",
    spellIds: [202138],
    classSlug: "demon-hunter",
    roles: ALL_ROLES,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "demon-hunter.purge.consume-magic",
    name: "Consume Magic",
    spellIds: [278326],
    classSlug: "demon-hunter",
    specSlugs: ["vengeance"],
    roles: TANK,
    category: "PURGE",
    sharedAcrossSpecs: false,
    cooldownSeconds: 10,
  }),
  rule({
    canonicalKey: "demon-hunter.defensive-minor.blur",
    name: "Blur",
    spellIds: [198589],
    classSlug: "demon-hunter",
    roles: TANK_DPS,
    category: "DEFENSIVE_MINOR",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "demon-hunter.defensive-major.demon-spikes",
    name: "Demon Spikes",
    spellIds: [203720],
    classSlug: "demon-hunter",
    specSlugs: ["vengeance"],
    roles: TANK,
    category: "DEFENSIVE_MAJOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 20,
  }),
  rule({
    canonicalKey: "demon-hunter.external-defensive.fiery-brand",
    name: "Fiery Brand",
    spellIds: [204021],
    classSlug: "demon-hunter",
    roles: TANK_DPS,
    category: "EXTERNAL_DEFENSIVE",
    availability: "TALENT",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "demon-hunter.group-utility.darkness",
    name: "Darkness",
    spellIds: [196718],
    classSlug: "demon-hunter",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    availability: "TALENT",
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "demon-hunter.immunity.netherwalk",
    name: "Netherwalk",
    spellIds: [196555],
    classSlug: "demon-hunter",
    specSlugs: ["havoc"],
    roles: DPS,
    category: "IMMUNITY",
    sharedAcrossSpecs: false,
    availability: "TALENT",
    cooldownSeconds: 180,
  }),
];
