import type { AbilityRule } from "../../types.js";
import { ALL_ROLES, DPS, HEALER, TANK, TANK_DPS, rule } from "../rule.js";

/** Druid survival / utility catalog (Retail M+). */
export const DRUID_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "druid.interrupt.skull-bash",
    name: "Skull Bash",
    spellIds: [106839],
    classSlug: "druid",
    specSlugs: ["feral", "guardian"],
    roles: TANK_DPS,
    category: "INTERRUPT",
    sharedAcrossSpecs: false,
    cooldownSeconds: 15,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "druid.interrupt.solar-beam",
    name: "Solar Beam",
    spellIds: [78675],
    classSlug: "druid",
    specSlugs: ["balance"],
    roles: DPS,
    category: "INTERRUPT",
    sharedAcrossSpecs: false,
    cooldownSeconds: 60,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "druid.hard-cc.mighty-bash",
    name: "Mighty Bash",
    spellIds: [5211],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "HARD_CC",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "druid.hard-cc.incapacitating-roar",
    name: "Incapacitating Roar",
    spellIds: [99],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "HARD_CC",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "druid.hard-cc.cyclone",
    name: "Cyclone",
    spellIds: [33786],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "HARD_CC",
    availability: "TALENT",
  }),
  rule({
    canonicalKey: "druid.hard-cc.hibernate",
    name: "Hibernate",
    spellIds: [2637],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "HARD_CC",
  }),
  rule({
    canonicalKey: "druid.soft-cc.typhoon",
    name: "Typhoon",
    spellIds: [132469],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "druid.soft-cc.ursols-vortex",
    name: "Ursol's Vortex",
    spellIds: [102793],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "druid.dispel.remove-corruption",
    name: "Remove Corruption",
    spellIds: [2782],
    classSlug: "druid",
    specSlugs: ["balance", "feral", "guardian"],
    roles: TANK_DPS,
    category: "DISPEL",
    sharedAcrossSpecs: false,
    cooldownSeconds: 8,
  }),
  rule({
    canonicalKey: "druid.dispel.natures-cure",
    name: "Nature's Cure",
    spellIds: [88423],
    classSlug: "druid",
    specSlugs: ["restoration"],
    roles: HEALER,
    category: "DISPEL",
    sharedAcrossSpecs: false,
    cooldownSeconds: 8,
  }),
  rule({
    canonicalKey: "druid.purge.soothe",
    name: "Soothe",
    spellIds: [2908],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "PURGE",
    cooldownSeconds: 10,
  }),
  rule({
    canonicalKey: "druid.defensive-minor.barkskin",
    name: "Barkskin",
    spellIds: [22812],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MINOR",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "druid.defensive-major.survival-instincts",
    name: "Survival Instincts",
    spellIds: [61336],
    classSlug: "druid",
    specSlugs: ["feral", "guardian"],
    roles: TANK_DPS,
    category: "DEFENSIVE_MAJOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "druid.self-heal.frenzied-regeneration",
    name: "Frenzied Regeneration",
    spellIds: [22842],
    classSlug: "druid",
    specSlugs: ["guardian"],
    roles: TANK,
    category: "SELF_HEAL",
    sharedAcrossSpecs: false,
    cooldownSeconds: 36,
  }),
  rule({
    canonicalKey: "druid.external-defensive.ironbark",
    name: "Ironbark",
    spellIds: [102342],
    classSlug: "druid",
    specSlugs: ["restoration"],
    roles: HEALER,
    category: "EXTERNAL_DEFENSIVE",
    sharedAcrossSpecs: false,
    cooldownSeconds: 90,
  }),
  rule({
    canonicalKey: "druid.group-utility.stampeding-roar",
    name: "Stampeding Roar",
    spellIds: [106898],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "druid.group-utility.innervate",
    name: "Innervate",
    spellIds: [29166],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "druid.movement-utility.dash",
    name: "Dash",
    spellIds: [1850],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "MOVEMENT_UTILITY",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "druid.battle-rez.rebirth",
    name: "Rebirth",
    spellIds: [20484],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "BATTLE_REZ",
    cooldownSeconds: 600,
  }),
];
