import type { AbilityRule } from "../../types.js";
import { ALL_ROLES, DPS, HEALER, TANK, TANK_DPS, rule, performanceCooldownRule } from "../rule.js";

/** Druid survival / utility catalog (Retail M+). */
export const DRUID_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "druid.interrupt.skull-bash",
    name: "Skull Bash",
    spellIds: [106839],
    // 93985 is the FR-locale spell ID reported by WCL for the same ability
    aliases: [93985],
    classSlug: "druid",
    specSlugs: ["feral", "guardian"],
    roles: TANK_DPS,
    category: "INTERRUPT",
    sharedAcrossSpecs: false,
    cooldownSeconds: 15,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "druid.interrupt.solar-beam",
    name: "Solar Beam",
    spellIds: [78675],
    classSlug: "druid",
    specSlugs: ["balance"],
    roles: DPS,
    category: "INTERRUPT",
    sharedAcrossSpecs: false,
    cooldownSeconds: 60,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "druid.hard-cc.mighty-bash",
    name: "Mighty Bash",
    spellIds: [5211],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "HARD_CC",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "druid.hard-cc.incapacitating-roar",
    name: "Incapacitating Roar",
    spellIds: [99],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "HARD_CC",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "druid.hard-cc.cyclone",
    name: "Cyclone",
    spellIds: [33786],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "HARD_CC",
    availability: "TALENT",
  }),
  rule({
    canonicalKey: "druid.hard-cc.hibernate",
    name: "Hibernate",
    spellIds: [2637],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "HARD_CC",
  }),
  rule({
    canonicalKey: "druid.soft-cc.typhoon",
    name: "Typhoon",
    spellIds: [132469],
    aliases: [61391],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 30,
    notes:
      "Alias 61391 is the retail cast/knockback debuff ID observed on Casts+Interrupts " +
      "(applydebuff) for 1WKcCz2BnAQmbhfq:1 — same canonical Typhoon activation, not a separate stop.",
  }),
  rule({
    canonicalKey: "druid.soft-cc.ursols-vortex",
    name: "Ursol's Vortex",
    spellIds: [102793],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "druid.dispel.remove-corruption",
    name: "Remove Corruption",
    spellIds: [2782],
    classSlug: "druid",
    specSlugs: ["balance", "feral", "guardian"],
    roles: TANK_DPS,
    category: "DISPEL",
    sharedAcrossSpecs: false,
    cooldownSeconds: 8,
  }),
  rule({
    canonicalKey: "druid.dispel.natures-cure",
    name: "Nature's Cure",
    spellIds: [88423],
    classSlug: "druid",
    specSlugs: ["restoration"],
    roles: HEALER,
    category: "DISPEL",
    sharedAcrossSpecs: false,
    cooldownSeconds: 8,
  }),
  rule({
    canonicalKey: "druid.purge.soothe",
    name: "Soothe",
    spellIds: [2908],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "PURGE",
    cooldownSeconds: 10,
  }),
  rule({
    canonicalKey: "druid.defensive-minor.barkskin",
    name: "Barkskin",
    spellIds: [22812],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MINOR",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "druid.defensive-major.survival-instincts",
    name: "Survival Instincts",
    spellIds: [61336],
    classSlug: "druid",
    specSlugs: ["feral", "guardian"],
    roles: TANK_DPS,
    category: "DEFENSIVE_MAJOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "druid.self-heal.frenzied-regeneration",
    name: "Frenzied Regeneration",
    spellIds: [22842],
    classSlug: "druid",
    specSlugs: ["guardian"],
    roles: TANK,
    category: "SELF_HEAL",
    sharedAcrossSpecs: false,
    cooldownSeconds: 36,
  }),
  rule({
    canonicalKey: "druid.external-defensive.ironbark",
    name: "Ironbark",
    spellIds: [102342],
    classSlug: "druid",
    specSlugs: ["restoration"],
    roles: HEALER,
    category: "EXTERNAL_DEFENSIVE",
    sharedAcrossSpecs: false,
    cooldownSeconds: 90,
  }),
  rule({
    canonicalKey: "druid.group-utility.stampeding-roar",
    name: "Stampeding Roar",
    spellIds: [106898],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "druid.group-utility.innervate",
    name: "Innervate",
    spellIds: [29166],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "druid.movement-utility.dash",
    name: "Dash",
    spellIds: [1850],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "MOVEMENT_UTILITY",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "druid.battle-rez.rebirth",
    name: "Rebirth",
    spellIds: [20484],
    classSlug: "druid",
    roles: ALL_ROLES,
    category: "BATTLE_REZ",
    cooldownSeconds: 600,
  }),

  // Performance offensive cooldowns (canonical AbilityRule entries).
    performanceCooldownRule({
      canonicalKey: "druid.offensive.celestial-alignment",
      name: "Celestial Alignment",
      spellIds: [194223],
      aliases: [383410],
      activationBuffIds: [194223, 383410],
      classSlug: "druid",
      specSlugs: ["balance"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 180,
      notes: "Alias covers Orbital Strike / alignment variants observed in WCL.",
    }),
    performanceCooldownRule({
      canonicalKey: "druid.offensive.incarnation-chosen-of-elune",
      name: "Incarnation: Chosen of Elune",
      spellIds: [102560],
      activationBuffIds: [102560],
      classSlug: "druid",
      specSlugs: ["balance"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 180,
      replacementFor: "druid.offensive.celestial-alignment",
    }),
    performanceCooldownRule({
      canonicalKey: "druid.offensive.convoke-the-spirits",
      name: "Convoke the Spirits",
      spellIds: [391528],
      classSlug: "druid",
      roles: [...DPS, ...TANK, ...HEALER],
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 120,
    }),
    performanceCooldownRule({
      canonicalKey: "druid.offensive.fury-of-elune",
      name: "Fury of Elune",
      spellIds: [202770],
      classSlug: "druid",
      specSlugs: ["balance"],
      roles: DPS,
      category: "OFFENSIVE_MINOR",
      availability: "TALENT",
      cooldownSeconds: 60,
    }),
    performanceCooldownRule({
      canonicalKey: "druid.offensive.force-of-nature",
      name: "Force of Nature",
      spellIds: [205636],
      classSlug: "druid",
      specSlugs: ["balance"],
      roles: DPS,
      category: "OFFENSIVE_MINOR",
      availability: "TALENT",
      cooldownSeconds: 60,
    }),
    performanceCooldownRule({
      canonicalKey: "druid.offensive.berserk-feral",
      name: "Berserk",
      spellIds: [106951],
      activationBuffIds: [106951],
      classSlug: "druid",
      specSlugs: ["feral"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 180,
    }),
    performanceCooldownRule({
      canonicalKey: "druid.offensive.incarnation-avatar-of-ashamane",
      name: "Incarnation: Avatar of Ashamane",
      spellIds: [102543],
      activationBuffIds: [102543],
      classSlug: "druid",
      specSlugs: ["feral"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 180,
      replacementFor: "druid.offensive.berserk-feral",
    }),
    performanceCooldownRule({
      canonicalKey: "druid.offensive.tigers-fury",
      name: "Tiger's Fury",
      spellIds: [5217],
      activationBuffIds: [5217],
      classSlug: "druid",
      specSlugs: ["feral"],
      roles: DPS,
      category: "OFFENSIVE_MINOR",
      availability: "BASELINE",
      cooldownSeconds: 30,
    }),
    performanceCooldownRule({
      canonicalKey: "druid.offensive.incarnation-guardian-of-ursoc",
      name: "Incarnation: Guardian of Ursoc",
      spellIds: [102558],
      activationSpellIds: [102558],
      activationBuffIds: [102558],
      classSlug: "druid",
      specSlugs: ["guardian"],
      roles: TANK,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 180,
      activationSource: "PLAYER_CAST",
      activationEventTypes: ["cast", "applybuff"],
    }),
    performanceCooldownRule({
      canonicalKey: "druid.offensive.rage-of-the-sleeper",
      name: "Rage of the Sleeper",
      spellIds: [200851],
      activationBuffIds: [200851],
      classSlug: "druid",
      specSlugs: ["guardian"],
      roles: TANK,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 90,
    }),
    performanceCooldownRule({
      canonicalKey: "druid.offensive.natures-vigil",
      name: "Nature's Vigil",
      spellIds: [124974],
      activationBuffIds: [124974],
      classSlug: "druid",
      roles: [...DPS, ...HEALER],
      category: "OFFENSIVE_MINOR",
      availability: "TALENT",
      cooldownSeconds: 90,
      notes: "Converts healing/damage; offensive throughput window for DPS and hybrid use.",
    }),
];
