import type { AbilityRule } from "../../types.js";
import { ALL_ROLES, DPS, HEALER, HEALER_DPS, rule, performanceCooldownRule } from "../rule.js";

/** Evoker survival / utility catalog (Retail M+). */
export const EVOKER_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "evoker.interrupt.quell",
    name: "Quell",
    spellIds: [351338],
    classSlug: "evoker",
    // Midnight: Preservation lost interrupt; Resto Shaman is the healer exception.
    specSlugs: ["devastation", "augmentation"],
    roles: DPS,
    category: "INTERRUPT",
    sharedAcrossSpecs: false,
    cooldownSeconds: 40,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "evoker.hard-cc.landslide",
    name: "Landslide",
    spellIds: [358385],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "HARD_CC",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "evoker.hard-cc.sleep-walk",
    name: "Sleep Walk",
    spellIds: [360806],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "HARD_CC",
    availability: "TALENT",
    cooldownSeconds: 15,
  }),
  rule({
    canonicalKey: "evoker.hard-cc.oppressing-roar",
    name: "Oppressing Roar",
    spellIds: [406971],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "HARD_CC",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "evoker.dispel.expunge",
    name: "Expunge",
    spellIds: [365585],
    classSlug: "evoker",
    specSlugs: ["devastation", "augmentation"],
    roles: DPS,
    category: "DISPEL",
    sharedAcrossSpecs: false,
    cooldownSeconds: 8,
  }),
  rule({
    canonicalKey: "evoker.dispel.naturalize",
    name: "Naturalize",
    spellIds: [360823],
    classSlug: "evoker",
    specSlugs: ["preservation"],
    roles: HEALER,
    category: "DISPEL",
    sharedAcrossSpecs: false,
    cooldownSeconds: 8,
  }),
  rule({
    canonicalKey: "evoker.defensive-minor.obsidian-scales",
    name: "Obsidian Scales",
    spellIds: [363916],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MINOR",
    cooldownSeconds: 90,
  }),
  rule({
    canonicalKey: "evoker.defensive-minor.renewing-blaze",
    name: "Renewing Blaze",
    spellIds: [374348],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MINOR",
    cooldownSeconds: 90,
  }),
  rule({
    canonicalKey: "evoker.dispel.cauterizing-flame",
    name: "Cauterizing Flame",
    spellIds: [374251],
    classSlug: "evoker",
    roles: HEALER_DPS,
    category: "DISPEL",
    availability: "TALENT",
    cooldownSeconds: 60,
    notes:
      "Talent dispel (bleed/poison/disease/curse) with heal component. Credited as Utility DISPEL; " +
      "verified on Dispels+Casts for 1WKcCz2BnAQmbhfq:1 (Litonfire).",
  }),
  rule({
    canonicalKey: "evoker.external-defensive.rescue",
    name: "Rescue",
    spellIds: [370665],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "EXTERNAL_DEFENSIVE",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "evoker.group-utility.zephyr",
    name: "Zephyr",
    spellIds: [374227],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "evoker.group-utility.time-spiral",
    name: "Time Spiral",
    spellIds: [374968],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "evoker.group-utility.rewind",
    name: "Rewind",
    spellIds: [363534],
    classSlug: "evoker",
    specSlugs: ["preservation"],
    roles: HEALER,
    category: "GROUP_UTILITY",
    sharedAcrossSpecs: false,
    cooldownSeconds: 240,
  }),
  rule({
    canonicalKey: "evoker.group-utility.dream-flight",
    name: "Dream Flight",
    spellIds: [359816],
    classSlug: "evoker",
    specSlugs: ["preservation"],
    roles: HEALER,
    category: "GROUP_UTILITY",
    sharedAcrossSpecs: false,
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "evoker.group-utility.blessing-of-the-bronze",
    name: "Blessing of the Bronze",
    spellIds: [364342],
    aliases: [381732],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    cooldownSeconds: 15,
  }),

  // Performance offensive cooldowns (canonical AbilityRule entries).
    performanceCooldownRule({
      canonicalKey: "evoker.offensive.dragonrage",
      name: "Dragonrage",
      spellIds: [375087],
      activationBuffIds: [375087],
      classSlug: "evoker",
      specSlugs: ["devastation"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 120,
    }),
    performanceCooldownRule({
      canonicalKey: "evoker.offensive.tip-the-scales",
      name: "Tip the Scales",
      spellIds: [370553],
      activationSpellIds: [370553],
      activationBuffIds: [370553],
      classSlug: "evoker",
      roles: [...DPS, ...HEALER],
      category: "OFFENSIVE_MINOR",
      availability: "BASELINE",
      cooldownSeconds: 120,
      activationSource: "PLAYER_CAST",
      activationEventTypes: ["cast", "applybuff"],
    }),
    performanceCooldownRule({
      canonicalKey: "evoker.offensive.deep-breath",
      name: "Deep Breath",
      spellIds: [357210],
      aliases: [433874],
      classSlug: "evoker",
      roles: [...DPS, ...HEALER],
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 120,
      notes: "Class deep breath; Breath of Eons is Augmentation replacement.",
    }),
    performanceCooldownRule({
      canonicalKey: "evoker.offensive.breath-of-eons",
      name: "Breath of Eons",
      spellIds: [403631],
      aliases: [442204],
      activationSpellIds: [403631, 442204],
      activationBuffIds: [403631, 442204],
      classSlug: "evoker",
      specSlugs: ["augmentation"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 120,
      replacementFor: "evoker.offensive.deep-breath",
      activationSource: "PLAYER_CAST",
      activationEventTypes: ["cast", "applybuff"],
      notes:
        "Augmentation Deep Breath replacement. Cast-primary; applybuff/removebuff of the same IDs correlate to the cast (Tip the Scales / CDR can compress gaps below 120s).",
    }),
    performanceCooldownRule({
      canonicalKey: "evoker.offensive.time-skip",
      name: "Time Skip",
      spellIds: [404977],
      classSlug: "evoker",
      specSlugs: ["augmentation"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 180,
    }),
    performanceCooldownRule({
      canonicalKey: "evoker.offensive.eternity-surge",
      name: "Eternity Surge",
      spellIds: [359073],
      aliases: [382411],
      classSlug: "evoker",
      specSlugs: ["devastation"],
      roles: DPS,
      category: "OFFENSIVE_MINOR",
      availability: "BASELINE",
      cooldownSeconds: 30,
      notes: "Empowered burst ability with cooldown — not a filler generator.",
    }),
    performanceCooldownRule({
      canonicalKey: "evoker.offensive.fire-breath",
      name: "Fire Breath",
      spellIds: [357208],
      aliases: [382266],
      activationSpellIds: [357208, 382266],
      activationBuffIds: [357208, 382266],
      classSlug: "evoker",
      roles: [...DPS, ...HEALER],
      category: "OFFENSIVE_MINOR",
      availability: "BASELINE",
      cooldownSeconds: 30,
      activationSource: "PLAYER_EMPOWERED_CAST",
      activationEventTypes: ["cast", "empowerstart", "empowerend", "applybuff"],
      notes:
        "Empowered class breath. One activation per empowerstart→cast/empowerend chain; Tip the Scales can reset CD (~25s observed gaps).",
    }),
];
