import type { AbilityRule } from "../../types.js";
import { ALL_ROLES, DPS, HEALER, HEALER_DPS, rule } from "../rule.js";

/** Evoker survival / utility catalog (Retail M+). */
export const EVOKER_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "evoker.interrupt.quell",
    name: "Quell",
    spellIds: [351338],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "INTERRUPT",
    cooldownSeconds: 40,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "evoker.hard-cc.landslide",
    name: "Landslide",
    spellIds: [358385],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "HARD_CC",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "evoker.hard-cc.sleep-walk",
    name: "Sleep Walk",
    spellIds: [360806],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "HARD_CC",
    availability: "TALENT",
    cooldownSeconds: 15,
  }),
  rule({
    canonicalKey: "evoker.hard-cc.oppressing-roar",
    name: "Oppressing Roar",
    spellIds: [406971],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "HARD_CC",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "evoker.dispel.expunge",
    name: "Expunge",
    spellIds: [365585],
    classSlug: "evoker",
    specSlugs: ["devastation", "augmentation"],
    roles: DPS,
    category: "DISPEL",
    sharedAcrossSpecs: false,
    cooldownSeconds: 8,
  }),
  rule({
    canonicalKey: "evoker.dispel.naturalize",
    name: "Naturalize",
    spellIds: [360823],
    classSlug: "evoker",
    specSlugs: ["preservation"],
    roles: HEALER,
    category: "DISPEL",
    sharedAcrossSpecs: false,
    cooldownSeconds: 8,
  }),
  rule({
    canonicalKey: "evoker.defensive-minor.obsidian-scales",
    name: "Obsidian Scales",
    spellIds: [363916],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MINOR",
    cooldownSeconds: 90,
  }),
  rule({
    canonicalKey: "evoker.defensive-minor.renewing-blaze",
    name: "Renewing Blaze",
    spellIds: [374348],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MINOR",
    cooldownSeconds: 90,
  }),
  rule({
    canonicalKey: "evoker.defensive-major.cauterizing-flame",
    name: "Cauterizing Flame",
    spellIds: [374251],
    classSlug: "evoker",
    roles: HEALER_DPS,
    category: "DEFENSIVE_MAJOR",
    availability: "TALENT",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "evoker.external-defensive.rescue",
    name: "Rescue",
    spellIds: [370665],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "EXTERNAL_DEFENSIVE",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "evoker.group-utility.zephyr",
    name: "Zephyr",
    spellIds: [374227],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "evoker.group-utility.time-spiral",
    name: "Time Spiral",
    spellIds: [374968],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "evoker.group-utility.rewind",
    name: "Rewind",
    spellIds: [363534],
    classSlug: "evoker",
    specSlugs: ["preservation"],
    roles: HEALER,
    category: "GROUP_UTILITY",
    sharedAcrossSpecs: false,
    cooldownSeconds: 240,
  }),
  rule({
    canonicalKey: "evoker.group-utility.dream-flight",
    name: "Dream Flight",
    spellIds: [359816],
    classSlug: "evoker",
    specSlugs: ["preservation"],
    roles: HEALER,
    category: "GROUP_UTILITY",
    sharedAcrossSpecs: false,
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "evoker.group-utility.blessing-of-the-bronze",
    name: "Blessing of the Bronze",
    spellIds: [364342],
    aliases: [381732],
    classSlug: "evoker",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    cooldownSeconds: 15,
  }),
];
