import type { AbilityRule } from "../../types.js";
import { DPS, rule, performanceCooldownRule } from "../rule.js";

/** Hunter survival / utility catalog (Retail M+). */
export const HUNTER_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "hunter.interrupt.counter-shot",
    name: "Counter Shot",
    spellIds: [147362],
    classSlug: "hunter",
    specSlugs: ["beast-mastery", "marksmanship"],
    roles: DPS,
    category: "INTERRUPT",
    sharedAcrossSpecs: false,
    cooldownSeconds: 24,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "hunter.interrupt.muzzle",
    name: "Muzzle",
    spellIds: [187707],
    classSlug: "hunter",
    specSlugs: ["survival"],
    roles: DPS,
    category: "INTERRUPT",
    sharedAcrossSpecs: false,
    cooldownSeconds: 15,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "hunter.hard-cc.freezing-trap",
    name: "Freezing Trap",
    spellIds: [187650],
    classSlug: "hunter",
    roles: DPS,
    category: "HARD_CC",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "hunter.hard-cc.intimidation",
    name: "Intimidation",
    spellIds: [19577],
    classSlug: "hunter",
    roles: DPS,
    category: "HARD_CC",
    availability: "TALENT",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "hunter.soft-cc.binding-shot",
    name: "Binding Shot",
    spellIds: [109248],
    classSlug: "hunter",
    roles: DPS,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 45,
  }),
  rule({
    canonicalKey: "hunter.purge.tranquilizing-shot",
    name: "Tranquilizing Shot",
    spellIds: [19801],
    classSlug: "hunter",
    roles: DPS,
    category: "PURGE",
    cooldownSeconds: 10,
  }),
  rule({
    canonicalKey: "hunter.defensive-minor.feign-death",
    name: "Feign Death",
    spellIds: [5384],
    classSlug: "hunter",
    roles: DPS,
    category: "DEFENSIVE_MINOR",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "hunter.defensive-major.aspect-of-the-turtle",
    name: "Aspect of the Turtle",
    spellIds: [186265],
    classSlug: "hunter",
    roles: DPS,
    category: "DEFENSIVE_MAJOR",
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "hunter.self-heal.exhilaration",
    name: "Exhilaration",
    spellIds: [109304],
    classSlug: "hunter",
    roles: DPS,
    category: "SELF_HEAL",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "hunter.external-defensive.roar-of-sacrifice",
    name: "Roar of Sacrifice",
    spellIds: [53480],
    classSlug: "hunter",
    roles: DPS,
    category: "EXTERNAL_DEFENSIVE",
    availability: "TALENT",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "hunter.group-utility.misdirection",
    name: "Misdirection",
    spellIds: [34477],
    classSlug: "hunter",
    roles: DPS,
    category: "GROUP_UTILITY",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "hunter.group-utility.masters-call",
    name: "Master's Call",
    spellIds: [272682],
    classSlug: "hunter",
    roles: DPS,
    category: "GROUP_UTILITY",
    cooldownSeconds: 45,
  }),
  rule({
    canonicalKey: "hunter.movement-utility.aspect-of-the-cheetah",
    name: "Aspect of the Cheetah",
    spellIds: [186257],
    classSlug: "hunter",
    roles: DPS,
    category: "MOVEMENT_UTILITY",
    cooldownSeconds: 180,
  }),

  // Performance offensive cooldowns (canonical AbilityRule entries).
    performanceCooldownRule({
      canonicalKey: "hunter.offensive.bestial-wrath",
      name: "Bestial Wrath",
      spellIds: [19574],
      activationBuffIds: [19574],
      classSlug: "hunter",
      specSlugs: ["beast-mastery"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 90,
    }),
    performanceCooldownRule({
      canonicalKey: "hunter.offensive.call-of-the-wild",
      name: "Call of the Wild",
      spellIds: [359844],
      activationBuffIds: [359844],
      classSlug: "hunter",
      specSlugs: ["beast-mastery"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 120,
    }),
    performanceCooldownRule({
      canonicalKey: "hunter.offensive.bloodshed",
      name: "Bloodshed",
      spellIds: [321530],
      classSlug: "hunter",
      specSlugs: ["beast-mastery"],
      roles: DPS,
      category: "OFFENSIVE_MINOR",
      availability: "TALENT",
      cooldownSeconds: 60,
    }),
    performanceCooldownRule({
      canonicalKey: "hunter.offensive.trueshot",
      name: "Trueshot",
      spellIds: [288613],
      activationBuffIds: [288613],
      classSlug: "hunter",
      specSlugs: ["marksmanship"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 120,
    }),
    performanceCooldownRule({
      canonicalKey: "hunter.offensive.volley",
      name: "Volley",
      spellIds: [260243],
      classSlug: "hunter",
      specSlugs: ["marksmanship"],
      roles: DPS,
      category: "OFFENSIVE_MINOR",
      availability: "TALENT",
      cooldownSeconds: 45,
    }),
    performanceCooldownRule({
      canonicalKey: "hunter.offensive.coordinated-assault",
      name: "Coordinated Assault",
      spellIds: [360952],
      activationBuffIds: [360952],
      classSlug: "hunter",
      specSlugs: ["survival"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 120,
    }),
    performanceCooldownRule({
      canonicalKey: "hunter.offensive.spearhead",
      name: "Spearhead",
      spellIds: [360966],
      activationBuffIds: [360966],
      classSlug: "hunter",
      specSlugs: ["survival"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 90,
    }),
    performanceCooldownRule({
      canonicalKey: "hunter.offensive.fury-of-the-eagle",
      name: "Fury of the Eagle",
      spellIds: [203415],
      classSlug: "hunter",
      specSlugs: ["survival"],
      roles: DPS,
      category: "OFFENSIVE_MINOR",
      availability: "TALENT",
      cooldownSeconds: 45,
    }),
];
