import type { AbilityRule } from "../../types.js";
import { ALL_ROLES, DPS, rule } from "../rule.js";

/** Mage survival / utility catalog (Retail M+). */
export const MAGE_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "mage.interrupt.counterspell",
    name: "Counterspell",
    spellIds: [2139],
    classSlug: "mage",
    roles: DPS,
    category: "INTERRUPT",
    cooldownSeconds: 24,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "mage.hard-cc.polymorph",
    name: "Polymorph",
    spellIds: [118],
    classSlug: "mage",
    roles: DPS,
    category: "HARD_CC",
  }),
  rule({
    canonicalKey: "mage.soft-cc.frost-nova",
    name: "Frost Nova",
    spellIds: [122],
    classSlug: "mage",
    roles: DPS,
    category: "SOFT_CC",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "mage.dispel.remove-curse",
    name: "Remove Curse",
    spellIds: [475],
    classSlug: "mage",
    roles: DPS,
    category: "DISPEL",
    cooldownSeconds: 8,
  }),
  rule({
    canonicalKey: "mage.purge.spell-steal",
    name: "Spell Steal",
    spellIds: [30449],
    classSlug: "mage",
    roles: DPS,
    category: "PURGE",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "mage.immunity.ice-block",
    name: "Ice Block",
    spellIds: [45438],
    classSlug: "mage",
    roles: DPS,
    category: "IMMUNITY",
    cooldownSeconds: 240,
  }),
  rule({
    canonicalKey: "mage.defensive-major.greater-invisibility",
    name: "Greater Invisibility",
    spellIds: [110959],
    classSlug: "mage",
    roles: DPS,
    category: "DEFENSIVE_MAJOR",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "mage.defensive-minor.alter-time",
    name: "Alter Time",
    spellIds: [342245],
    classSlug: "mage",
    roles: DPS,
    category: "DEFENSIVE_MINOR",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "mage.defensive-minor.mirror-image",
    name: "Mirror Image",
    spellIds: [55342],
    classSlug: "mage",
    roles: DPS,
    category: "DEFENSIVE_MINOR",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "mage.group-utility.mass-barrier",
    name: "Mass Barrier",
    spellIds: [414660],
    classSlug: "mage",
    roles: DPS,
    category: "GROUP_UTILITY",
    availability: "TALENT",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "mage.bloodlust.time-warp",
    name: "Time Warp",
    spellIds: [80353],
    classSlug: "mage",
    roles: DPS,
    category: "BLOODLUST",
    cooldownSeconds: 600,
  }),
  rule({
    canonicalKey: "mage.movement-utility.blink",
    name: "Blink",
    spellIds: [1953],
    classSlug: "mage",
    roles: DPS,
    category: "MOVEMENT_UTILITY",
    cooldownSeconds: 15,
  }),
  rule({
    canonicalKey: "mage.movement-utility.shimmer",
    name: "Shimmer",
    spellIds: [212653],
    classSlug: "mage",
    roles: DPS,
    category: "MOVEMENT_UTILITY",
    availability: "TALENT",
    cooldownSeconds: 25,
  }),
];
