import type { AbilityRule } from "../../types.js";
import { ALL_ROLES, DPS, HEALER, HEALER_DPS, TANK, TANK_DPS, rule, performanceCooldownRule } from "../rule.js";

/** Monk survival / utility catalog (Retail M+). */
export const MONK_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "monk.interrupt.spear-hand-strike",
    name: "Spear Hand Strike",
    spellIds: [116705],
    classSlug: "monk",
    // Midnight: Mistweaver no longer has an interrupt; WW + Brewmaster only.
    specSlugs: ["brewmaster", "windwalker"],
    roles: TANK_DPS,
    category: "INTERRUPT",
    sharedAcrossSpecs: false,
    cooldownSeconds: 15,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "monk.hard-cc.paralysis",
    name: "Paralysis",
    spellIds: [115078],
    classSlug: "monk",
    roles: ALL_ROLES,
    category: "HARD_CC",
    cooldownSeconds: 45,
  }),
  rule({
    canonicalKey: "monk.hard-cc.leg-sweep",
    name: "Leg Sweep",
    spellIds: [119381],
    classSlug: "monk",
    roles: ALL_ROLES,
    category: "HARD_CC",
    cooldownSeconds: 45,
  }),
  rule({
    canonicalKey: "monk.soft-cc.ring-of-peace",
    name: "Ring of Peace",
    spellIds: [116844],
    classSlug: "monk",
    roles: ALL_ROLES,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 45,
  }),
  rule({
    canonicalKey: "monk.dispel.detox",
    name: "Detox",
    spellIds: [115450],
    classSlug: "monk",
    specSlugs: ["mistweaver", "windwalker"],
    roles: HEALER_DPS,
    category: "DISPEL",
    sharedAcrossSpecs: false,
    cooldownSeconds: 8,
  }),
  rule({
    canonicalKey: "monk.defensive-major.fortifying-brew",
    name: "Fortifying Brew",
    spellIds: [115203],
    classSlug: "monk",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MAJOR",
    cooldownSeconds: 360,
  }),
  rule({
    canonicalKey: "monk.defensive-major.touch-of-karma",
    name: "Touch of Karma",
    spellIds: [122470],
    classSlug: "monk",
    specSlugs: ["windwalker"],
    roles: DPS,
    category: "DEFENSIVE_MAJOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "monk.defensive-major.diffuse-magic",
    name: "Diffuse Magic",
    spellIds: [122783],
    classSlug: "monk",
    specSlugs: ["brewmaster", "windwalker"],
    roles: TANK_DPS,
    category: "DEFENSIVE_MAJOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 90,
  }),
  rule({
    canonicalKey: "monk.external-defensive.life-cocoon",
    name: "Life Cocoon",
    spellIds: [116849],
    classSlug: "monk",
    specSlugs: ["mistweaver"],
    roles: HEALER,
    category: "EXTERNAL_DEFENSIVE",
    sharedAcrossSpecs: false,
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "monk.group-utility.revival",
    name: "Revival",
    spellIds: [115310],
    classSlug: "monk",
    specSlugs: ["mistweaver"],
    roles: HEALER,
    category: "GROUP_UTILITY",
    sharedAcrossSpecs: false,
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "monk.group-utility.tigers-lust",
    name: "Tiger's Lust",
    spellIds: [116841],
    classSlug: "monk",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "monk.defensive-minor.zen-meditation",
    name: "Zen Meditation",
    spellIds: [115176],
    classSlug: "monk",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MINOR",
    cooldownSeconds: 300,
  }),
  rule({
    canonicalKey: "monk.movement-utility.transcendence-transfer",
    name: "Transcendence: Transfer",
    spellIds: [119996],
    classSlug: "monk",
    roles: ALL_ROLES,
    category: "MOVEMENT_UTILITY",
    cooldownSeconds: 45,
  }),

  // Performance offensive cooldowns (canonical AbilityRule entries).
    performanceCooldownRule({
      canonicalKey: "monk.offensive.storm-earth-and-fire",
      name: "Storm, Earth, and Fire",
      spellIds: [137639],
      activationBuffIds: [137639],
      activationSpellIds: [137639],
      classSlug: "monk",
      specSlugs: ["windwalker"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 90,
      charges: 2,
      activationSource: "PLAYER_BUFF",
      activationEventTypes: ["applybuff", "cast", "begincast"],
    }),
    performanceCooldownRule({
      canonicalKey: "monk.offensive.invoke-xuen",
      name: "Invoke Xuen, the White Tiger",
      spellIds: [123904],
      classSlug: "monk",
      specSlugs: ["windwalker"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 120,
      sourceOwnership: "ANY_OWNED",
    }),
    performanceCooldownRule({
      canonicalKey: "monk.offensive.strike-of-the-windlord",
      name: "Strike of the Windlord",
      spellIds: [392983],
      classSlug: "monk",
      specSlugs: ["windwalker"],
      roles: DPS,
      category: "OFFENSIVE_MINOR",
      availability: "TALENT",
      cooldownSeconds: 40,
    }),
    performanceCooldownRule({
      canonicalKey: "monk.offensive.weapons-of-order",
      name: "Weapons of Order",
      spellIds: [387184],
      activationBuffIds: [387184],
      classSlug: "monk",
      specSlugs: ["brewmaster", "windwalker"],
      roles: [...TANK, ...DPS],
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 120,
    }),
    performanceCooldownRule({
      canonicalKey: "monk.offensive.invoke-niuzao",
      name: "Invoke Niuzao, the Black Ox",
      spellIds: [132578],
      classSlug: "monk",
      specSlugs: ["brewmaster"],
      roles: TANK,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 180,
      sourceOwnership: "ANY_OWNED",
    }),
    performanceCooldownRule({
      canonicalKey: "monk.offensive.exploding-keg",
      name: "Exploding Keg",
      spellIds: [325153],
      classSlug: "monk",
      specSlugs: ["brewmaster"],
      roles: TANK,
      category: "OFFENSIVE_MINOR",
      availability: "TALENT",
      cooldownSeconds: 60,
    }),
    performanceCooldownRule({
      canonicalKey: "monk.offensive.invoke-chiji",
      name: "Invoke Chi-Ji, the Red Crane",
      spellIds: [325197],
      activationSpellIds: [325197],
      classSlug: "monk",
      specSlugs: ["mistweaver"],
      roles: HEALER,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 180,
      sourceOwnership: "ANY_OWNED",
      activationSource: "PLAYER_CAST",
      activationEventTypes: ["cast"],
      notes: "Mistweaver celestial with damage component; Yu'lon is healing-primary alternative.",
    }),
    performanceCooldownRule({
      canonicalKey: "monk.offensive.invoke-yulon",
      name: "Invoke Yu'lon, the Jade Serpent",
      spellIds: [322118],
      classSlug: "monk",
      specSlugs: ["mistweaver"],
      roles: HEALER,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 180,
      sourceOwnership: "ANY_OWNED",
      notes: "Primarily healing celestial; retained so Mistweaver has reviewed coverage. Revisit if Performance excludes healer-only CDs.",
    }),
];
