import type { AbilityRule } from "../../types.js";
import { ALL_ROLES, DPS, HEALER, HEALER_DPS, TANK, TANK_DPS, rule } from "../rule.js";

/** Monk survival / utility catalog (Retail M+). */
export const MONK_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "monk.interrupt.spear-hand-strike",
    name: "Spear Hand Strike",
    spellIds: [116705],
    classSlug: "monk",
    roles: ALL_ROLES,
    category: "INTERRUPT",
    cooldownSeconds: 15,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "monk.hard-cc.paralysis",
    name: "Paralysis",
    spellIds: [115078],
    classSlug: "monk",
    roles: ALL_ROLES,
    category: "HARD_CC",
    cooldownSeconds: 45,
  }),
  rule({
    canonicalKey: "monk.hard-cc.leg-sweep",
    name: "Leg Sweep",
    spellIds: [119381],
    classSlug: "monk",
    roles: ALL_ROLES,
    category: "HARD_CC",
    cooldownSeconds: 45,
  }),
  rule({
    canonicalKey: "monk.soft-cc.ring-of-peace",
    name: "Ring of Peace",
    spellIds: [116844],
    classSlug: "monk",
    roles: ALL_ROLES,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 45,
  }),
  rule({
    canonicalKey: "monk.dispel.detox",
    name: "Detox",
    spellIds: [115450],
    classSlug: "monk",
    specSlugs: ["mistweaver", "windwalker"],
    roles: HEALER_DPS,
    category: "DISPEL",
    sharedAcrossSpecs: false,
    cooldownSeconds: 8,
  }),
  rule({
    canonicalKey: "monk.defensive-major.fortifying-brew",
    name: "Fortifying Brew",
    spellIds: [115203],
    classSlug: "monk",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MAJOR",
    cooldownSeconds: 360,
  }),
  rule({
    canonicalKey: "monk.defensive-major.touch-of-karma",
    name: "Touch of Karma",
    spellIds: [122470],
    classSlug: "monk",
    specSlugs: ["windwalker"],
    roles: DPS,
    category: "DEFENSIVE_MAJOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "monk.defensive-major.diffuse-magic",
    name: "Diffuse Magic",
    spellIds: [122783],
    classSlug: "monk",
    specSlugs: ["brewmaster", "windwalker"],
    roles: TANK_DPS,
    category: "DEFENSIVE_MAJOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 90,
  }),
  rule({
    canonicalKey: "monk.external-defensive.life-cocoon",
    name: "Life Cocoon",
    spellIds: [116849],
    classSlug: "monk",
    specSlugs: ["mistweaver"],
    roles: HEALER,
    category: "EXTERNAL_DEFENSIVE",
    sharedAcrossSpecs: false,
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "monk.group-utility.revival",
    name: "Revival",
    spellIds: [115310],
    classSlug: "monk",
    specSlugs: ["mistweaver"],
    roles: HEALER,
    category: "GROUP_UTILITY",
    sharedAcrossSpecs: false,
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "monk.group-utility.tigers-lust",
    name: "Tiger's Lust",
    spellIds: [116841],
    classSlug: "monk",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "monk.defensive-minor.zen-meditation",
    name: "Zen Meditation",
    spellIds: [115176],
    classSlug: "monk",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MINOR",
    cooldownSeconds: 300,
  }),
  rule({
    canonicalKey: "monk.movement-utility.transcendence-transfer",
    name: "Transcendence: Transfer",
    spellIds: [119996],
    classSlug: "monk",
    roles: ALL_ROLES,
    category: "MOVEMENT_UTILITY",
    cooldownSeconds: 45,
  }),
];
