import type { AbilityRule } from "../../types.js";
import { ALL_ROLES, HEALER, TANK, TANK_DPS, rule } from "../rule.js";

/** Paladin survival / utility catalog (Retail M+). */
export const PALADIN_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "paladin.interrupt.rebuke",
    name: "Rebuke",
    spellIds: [96231],
    classSlug: "paladin",
    roles: ALL_ROLES,
    category: "INTERRUPT",
    cooldownSeconds: 15,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "paladin.hard-cc.hammer-of-justice",
    name: "Hammer of Justice",
    spellIds: [853],
    classSlug: "paladin",
    roles: ALL_ROLES,
    category: "HARD_CC",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "paladin.dispel.cleanse",
    name: "Cleanse",
    spellIds: [4987],
    classSlug: "paladin",
    specSlugs: ["holy"],
    roles: HEALER,
    category: "DISPEL",
    sharedAcrossSpecs: false,
    cooldownSeconds: 8,
  }),
  rule({
    canonicalKey: "paladin.dispel.cleanse-toxins",
    name: "Cleanse Toxins",
    spellIds: [213644],
    classSlug: "paladin",
    specSlugs: ["protection", "retribution"],
    roles: TANK_DPS,
    category: "DISPEL",
    sharedAcrossSpecs: false,
    cooldownSeconds: 8,
  }),
  rule({
    canonicalKey: "paladin.immunity.divine-shield",
    name: "Divine Shield",
    spellIds: [642],
    classSlug: "paladin",
    roles: ALL_ROLES,
    category: "IMMUNITY",
    cooldownSeconds: 300,
  }),
  rule({
    canonicalKey: "paladin.defensive-major.divine-protection",
    name: "Divine Protection",
    spellIds: [498],
    classSlug: "paladin",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MAJOR",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "paladin.defensive-major.ardent-defender",
    name: "Ardent Defender",
    spellIds: [31850],
    classSlug: "paladin",
    specSlugs: ["protection"],
    roles: TANK,
    category: "DEFENSIVE_MAJOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "paladin.defensive-major.guardian-of-ancient-kings",
    name: "Guardian of Ancient Kings",
    spellIds: [86659],
    classSlug: "paladin",
    specSlugs: ["protection"],
    roles: TANK,
    category: "DEFENSIVE_MAJOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "paladin.self-heal.lay-on-hands",
    name: "Lay on Hands",
    spellIds: [633],
    classSlug: "paladin",
    roles: ALL_ROLES,
    category: "SELF_HEAL",
    cooldownSeconds: 600,
  }),
  rule({
    canonicalKey: "paladin.external-defensive.blessing-of-protection",
    name: "Blessing of Protection",
    spellIds: [1022],
    classSlug: "paladin",
    roles: ALL_ROLES,
    category: "EXTERNAL_DEFENSIVE",
    cooldownSeconds: 300,
  }),
  rule({
    canonicalKey: "paladin.external-defensive.blessing-of-sacrifice",
    name: "Blessing of Sacrifice",
    spellIds: [6940],
    classSlug: "paladin",
    roles: ALL_ROLES,
    category: "EXTERNAL_DEFENSIVE",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "paladin.external-defensive.blessing-of-spellwarding",
    name: "Blessing of Spellwarding",
    spellIds: [204018],
    classSlug: "paladin",
    roles: ALL_ROLES,
    category: "EXTERNAL_DEFENSIVE",
    availability: "TALENT",
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "paladin.group-utility.blessing-of-freedom",
    name: "Blessing of Freedom",
    spellIds: [1044],
    classSlug: "paladin",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    cooldownSeconds: 25,
  }),
  rule({
    canonicalKey: "paladin.battle-rez.intercession",
    name: "Intercession",
    spellIds: [391054],
    classSlug: "paladin",
    roles: ALL_ROLES,
    category: "BATTLE_REZ",
    cooldownSeconds: 600,
  }),
];
