import type { AbilityRule } from "../../types.js";
import { ALL_ROLES, DPS, HEALER, HEALER_DPS, rule } from "../rule.js";

/** Priest survival / utility catalog (Retail M+). */
export const PRIEST_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "priest.interrupt.silence",
    name: "Silence",
    spellIds: [15487],
    classSlug: "priest",
    specSlugs: ["shadow"],
    roles: DPS,
    category: "INTERRUPT",
    sharedAcrossSpecs: false,
    cooldownSeconds: 45,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "priest.soft-cc.psychic-scream",
    name: "Psychic Scream",
    spellIds: [8122],
    classSlug: "priest",
    roles: ALL_ROLES,
    category: "SOFT_CC",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "priest.hard-cc.dominate-mind",
    name: "Dominate Mind",
    spellIds: [205364],
    classSlug: "priest",
    specSlugs: ["shadow"],
    roles: DPS,
    category: "HARD_CC",
    sharedAcrossSpecs: false,
    availability: "TALENT",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "priest.dispel.purify",
    name: "Purify",
    spellIds: [527],
    classSlug: "priest",
    specSlugs: ["discipline", "holy"],
    roles: HEALER,
    category: "DISPEL",
    sharedAcrossSpecs: false,
    cooldownSeconds: 8,
  }),
  rule({
    canonicalKey: "priest.dispel.purify-disease",
    name: "Purify Disease",
    spellIds: [213634],
    classSlug: "priest",
    roles: ALL_ROLES,
    category: "DISPEL",
    cooldownSeconds: 8,
  }),
  rule({
    canonicalKey: "priest.dispel.mass-dispel",
    name: "Mass Dispel",
    spellIds: [32375],
    classSlug: "priest",
    roles: HEALER_DPS,
    category: "DISPEL",
    cooldownSeconds: 45,
  }),
  rule({
    canonicalKey: "priest.defensive-minor.fade",
    name: "Fade",
    spellIds: [586],
    classSlug: "priest",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MINOR",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "priest.self-heal.desperate-prayer",
    name: "Desperate Prayer",
    spellIds: [19236],
    classSlug: "priest",
    roles: ALL_ROLES,
    category: "SELF_HEAL",
    cooldownSeconds: 90,
  }),
  rule({
    canonicalKey: "priest.defensive-major.dispersion",
    name: "Dispersion",
    spellIds: [47585],
    classSlug: "priest",
    specSlugs: ["shadow"],
    roles: DPS,
    category: "DEFENSIVE_MAJOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "priest.group-utility.power-word-barrier",
    name: "Power Word: Barrier",
    spellIds: [62618],
    classSlug: "priest",
    specSlugs: ["discipline"],
    roles: HEALER,
    category: "GROUP_UTILITY",
    sharedAcrossSpecs: false,
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "priest.external-defensive.pain-suppression",
    name: "Pain Suppression",
    spellIds: [33206],
    classSlug: "priest",
    specSlugs: ["discipline"],
    roles: HEALER,
    category: "EXTERNAL_DEFENSIVE",
    sharedAcrossSpecs: false,
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "priest.external-defensive.guardian-spirit",
    name: "Guardian Spirit",
    spellIds: [47788],
    classSlug: "priest",
    specSlugs: ["holy"],
    roles: HEALER,
    category: "EXTERNAL_DEFENSIVE",
    sharedAcrossSpecs: false,
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "priest.group-utility.leap-of-faith",
    name: "Leap of Faith",
    spellIds: [73325],
    classSlug: "priest",
    roles: HEALER_DPS,
    category: "GROUP_UTILITY",
    cooldownSeconds: 90,
  }),
  rule({
    canonicalKey: "priest.group-utility.power-infusion",
    name: "Power Infusion",
    spellIds: [10060],
    classSlug: "priest",
    roles: HEALER_DPS,
    category: "GROUP_UTILITY",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "priest.movement-utility.angelic-feather",
    name: "Angelic Feather",
    spellIds: [121536],
    classSlug: "priest",
    roles: ALL_ROLES,
    category: "MOVEMENT_UTILITY",
    cooldownSeconds: 20,
  }),
];
