import type { AbilityRule } from "../../types.js";
import { DPS, rule } from "../rule.js";

/** Rogue survival / utility catalog (Retail M+). */
export const ROGUE_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "rogue.interrupt.kick",
    name: "Kick",
    spellIds: [1766],
    classSlug: "rogue",
    roles: DPS,
    category: "INTERRUPT",
    cooldownSeconds: 15,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "rogue.hard-cc.cheap-shot",
    name: "Cheap Shot",
    spellIds: [1833],
    classSlug: "rogue",
    roles: DPS,
    category: "HARD_CC",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "rogue.hard-cc.kidney-shot",
    name: "Kidney Shot",
    spellIds: [408],
    classSlug: "rogue",
    roles: DPS,
    category: "HARD_CC",
    cooldownSeconds: 20,
  }),
  rule({
    canonicalKey: "rogue.hard-cc.blind",
    name: "Blind",
    spellIds: [2094],
    classSlug: "rogue",
    roles: DPS,
    category: "HARD_CC",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "rogue.hard-cc.gouge",
    name: "Gouge",
    spellIds: [1776],
    classSlug: "rogue",
    roles: DPS,
    category: "HARD_CC",
    cooldownSeconds: 15,
  }),
  rule({
    canonicalKey: "rogue.soft-cc.smoke-bomb",
    name: "Smoke Bomb",
    spellIds: [212182],
    classSlug: "rogue",
    roles: DPS,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "rogue.immunity.cloak-of-shadows",
    name: "Cloak of Shadows",
    spellIds: [31224],
    classSlug: "rogue",
    roles: DPS,
    category: "IMMUNITY",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "rogue.defensive-major.evasion",
    name: "Evasion",
    spellIds: [5277],
    classSlug: "rogue",
    roles: DPS,
    category: "DEFENSIVE_MAJOR",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "rogue.defensive-minor.feint",
    name: "Feint",
    spellIds: [1966],
    classSlug: "rogue",
    roles: DPS,
    category: "DEFENSIVE_MINOR",
    cooldownSeconds: 15,
  }),
  rule({
    canonicalKey: "rogue.self-heal.crimson-vial",
    name: "Crimson Vial",
    spellIds: [185311],
    classSlug: "rogue",
    roles: DPS,
    category: "SELF_HEAL",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "rogue.purge.shiv",
    name: "Shiv",
    spellIds: [5938],
    classSlug: "rogue",
    roles: DPS,
    category: "PURGE",
    cooldownSeconds: 25,
  }),
  rule({
    canonicalKey: "rogue.group-utility.tricks-of-the-trade",
    name: "Tricks of the Trade",
    spellIds: [57934],
    classSlug: "rogue",
    roles: DPS,
    category: "GROUP_UTILITY",
    cooldownSeconds: 30,
  }),
];
