import type { AbilityRule } from "../../types.js";
import { ALL_ROLES, DPS, HEALER, HEALER_DPS, rule, performanceCooldownRule } from "../rule.js";

/** Shaman survival / utility catalog (Retail M+). */
export const SHAMAN_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "shaman.interrupt.wind-shear",
    name: "Wind Shear",
    spellIds: [57994],
    classSlug: "shaman",
    roles: ALL_ROLES,
    category: "INTERRUPT",
    cooldownSeconds: 12,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "shaman.hard-cc.hex",
    name: "Hex",
    spellIds: [51514],
    classSlug: "shaman",
    roles: ALL_ROLES,
    category: "HARD_CC",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "shaman.hard-cc.capacitor-totem",
    name: "Capacitor Totem",
    spellIds: [192058],
    classSlug: "shaman",
    roles: ALL_ROLES,
    category: "HARD_CC",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "shaman.dispel.purify-spirit",
    name: "Purify Spirit",
    spellIds: [77130],
    classSlug: "shaman",
    specSlugs: ["restoration"],
    roles: HEALER,
    category: "DISPEL",
    sharedAcrossSpecs: false,
    cooldownSeconds: 8,
  }),
  rule({
    canonicalKey: "shaman.dispel.cleanse-spirit",
    name: "Cleanse Spirit",
    spellIds: [51886],
    classSlug: "shaman",
    specSlugs: ["elemental", "enhancement"],
    roles: DPS,
    category: "DISPEL",
    sharedAcrossSpecs: false,
    cooldownSeconds: 8,
  }),
  rule({
    canonicalKey: "shaman.dispel.poison-cleansing-totem",
    name: "Poison Cleansing Totem",
    spellIds: [383013],
    classSlug: "shaman",
    roles: ALL_ROLES,
    category: "DISPEL",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "shaman.purge.purge",
    name: "Purge",
    spellIds: [370],
    classSlug: "shaman",
    roles: ALL_ROLES,
    category: "PURGE",
    cooldownSeconds: 6,
  }),
  rule({
    canonicalKey: "shaman.purge.greater-purge",
    name: "Greater Purge",
    spellIds: [378773],
    classSlug: "shaman",
    roles: ALL_ROLES,
    category: "PURGE",
    availability: "TALENT",
    cooldownSeconds: 6,
  }),
  rule({
    canonicalKey: "shaman.defensive-major.astral-shift",
    name: "Astral Shift",
    spellIds: [108271],
    classSlug: "shaman",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MAJOR",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "shaman.active-heal.healing-surge",
    name: "Healing Surge",
    spellIds: [8004],
    classSlug: "shaman",
    specSlugs: ["enhancement"],
    roles: DPS,
    category: "SELF_HEAL",
    sharedAcrossSpecs: false,
    survivalActiveHeal: true,
    cooldownSeconds: 0,
  }),
  rule({
    canonicalKey: "shaman.group-utility.spirit-link-totem",
    name: "Spirit Link Totem",
    spellIds: [98008],
    classSlug: "shaman",
    specSlugs: ["restoration"],
    roles: HEALER,
    category: "GROUP_UTILITY",
    sharedAcrossSpecs: false,
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "shaman.group-utility.tremor-totem",
    name: "Tremor Totem",
    spellIds: [8143],
    classSlug: "shaman",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "shaman.group-utility.wind-rush-totem",
    name: "Wind Rush Totem",
    spellIds: [192077],
    classSlug: "shaman",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    availability: "TALENT",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "shaman.group-utility.earth-elemental",
    name: "Earth Elemental",
    spellIds: [198103],
    classSlug: "shaman",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    availability: "TALENT",
    cooldownSeconds: 300,
  }),
  rule({
    canonicalKey: "shaman.group-utility.spiritwalkers-grace",
    name: "Spiritwalker's Grace",
    spellIds: [79206],
    classSlug: "shaman",
    roles: HEALER_DPS,
    category: "GROUP_UTILITY",
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "shaman.bloodlust.bloodlust",
    name: "Bloodlust / Heroism",
    spellIds: [2825],
    aliases: [32182],
    classSlug: "shaman",
    roles: ALL_ROLES,
    category: "BLOODLUST",
    cooldownSeconds: 600,
    notes: "Alliance Heroism (32182) is an alias of Horde Bloodlust.",
  }),

  // Performance offensive cooldowns (canonical AbilityRule entries).
    performanceCooldownRule({
      canonicalKey: "shaman.offensive.stormkeeper",
      name: "Stormkeeper",
      spellIds: [191634],
      aliases: [383009],
      activationBuffIds: [191634, 383009],
      classSlug: "shaman",
      specSlugs: ["elemental", "enhancement"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 60,
    }),
    performanceCooldownRule({
      canonicalKey: "shaman.offensive.ascendance-elemental",
      name: "Ascendance",
      spellIds: [114050],
      activationBuffIds: [114050],
      classSlug: "shaman",
      specSlugs: ["elemental"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 180,
    }),
    performanceCooldownRule({
      canonicalKey: "shaman.offensive.fire-elemental",
      name: "Fire Elemental",
      spellIds: [198067],
      aliases: [192249],
      classSlug: "shaman",
      specSlugs: ["elemental"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 150,
      sourceOwnership: "ANY_OWNED",
      notes: "Storm Elemental is the talent replacement alias.",
    }),
    performanceCooldownRule({
      canonicalKey: "shaman.offensive.ascendance-enhancement",
      name: "Ascendance",
      spellIds: [114051],
      activationBuffIds: [114051],
      classSlug: "shaman",
      specSlugs: ["enhancement"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 180,
    }),
    performanceCooldownRule({
      canonicalKey: "shaman.offensive.feral-spirit",
      name: "Feral Spirit",
      spellIds: [51533],
      classSlug: "shaman",
      specSlugs: ["enhancement"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 90,
      sourceOwnership: "ANY_OWNED",
    }),
    performanceCooldownRule({
      canonicalKey: "shaman.offensive.doom-winds",
      name: "Doom Winds",
      spellIds: [384352],
      activationBuffIds: [384352],
      classSlug: "shaman",
      specSlugs: ["enhancement"],
      roles: DPS,
      category: "OFFENSIVE_MINOR",
      availability: "TALENT",
      cooldownSeconds: 60,
    }),
    performanceCooldownRule({
      canonicalKey: "shaman.offensive.primordial-wave",
      name: "Primordial Wave",
      spellIds: [375982],
      classSlug: "shaman",
      specSlugs: ["elemental", "enhancement"],
      roles: DPS,
      category: "OFFENSIVE_MINOR",
      availability: "TALENT",
      cooldownSeconds: 30,
    }),
];
