import type { AbilityRule } from "../../types.js";
import { DPS, rule, performanceCooldownRule } from "../rule.js";

const WARLOCK_SPECS = ["affliction", "demonology", "destruction"] as const;

/**
 * Warlock catalog (all specs). Demonology remains the primary live validation fixture.
 * Spell IDs from repository fixture warlock-demonology-tww-1 plus class-wide expansions.
 */
export const WARLOCK_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "warlock.interrupt.spell-lock",
    name: "Spell Lock",
    spellIds: [19647],
    classSlug: "warlock",
    roles: DPS,
    category: "INTERRUPT",
    sourceOwnership: "PET",
    availability: "PET_DEPENDENT",
    cooldownSeconds: 24,
    interruptProfile: "PET_DEPENDENT",
    requiresSuccessfulTarget: true,
    provenance: {
      source: "REPOSITORY_FIXTURE",
      sourceId: "felhunter",
      verifiedAt: "2026-07-28",
      gameVersion: "12.0.0",
      notes: "Felhunter interrupt; attributed to player.",
    },
  }),
  rule({
    canonicalKey: "warlock.interrupt.axe-toss",
    name: "Axe Toss",
    spellIds: [89766],
    aliases: [347008, 119914],
    classSlug: "warlock",
    specSlugs: ["demonology"],
    roles: DPS,
    category: "INTERRUPT",
    sourceOwnership: "PET",
    sharedAcrossSpecs: false,
    availability: "PET_DEPENDENT",
    cooldownSeconds: 30,
    interruptProfile: "CONSTRAINED_CONTROL",
    requiresSuccessfulTarget: true,
    provenance: {
      source: "REPOSITORY_FIXTURE",
      sourceId: "felguard",
      verifiedAt: "2026-08-05",
      gameVersion: "12.0.0",
      notes:
        "347008 = Felguard interrupt stream; 119914 = player Command Demon cast observed on Casts (1WKcCz2BnAQmbhfq:1). Stun/control side-effect constrains practical interrupt frequency.",
    },
  }),
  rule({
    canonicalKey: "warlock.interrupt.optical-blast",
    name: "Optical Blast",
    spellIds: [119910],
    aliases: [115781],
    classSlug: "warlock",
    roles: DPS,
    category: "INTERRUPT",
    sourceOwnership: "PET",
    availability: "PET_DEPENDENT",
    cooldownSeconds: 24,
    interruptProfile: "PET_DEPENDENT",
    requiresSuccessfulTarget: true,
    supportCertainty: "uncertain",
    notes: "Observer / Command Demon interrupt variant; alias retained for WCL cast ID drift.",
  }),
  rule({
    canonicalKey: "warlock.hard-cc.shadowfury",
    name: "Shadowfury",
    spellIds: [30283],
    classSlug: "warlock",
    specSlugs: [...WARLOCK_SPECS],
    roles: DPS,
    category: "HARD_CC",
    availability: "BASELINE",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "warlock.soft-cc.mortal-coil",
    name: "Mortal Coil",
    spellIds: [6789],
    classSlug: "warlock",
    roles: DPS,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 45,
  }),
  rule({
    canonicalKey: "warlock.soft-cc.fear",
    name: "Fear",
    spellIds: [5782],
    classSlug: "warlock",
    roles: DPS,
    category: "SOFT_CC",
    availability: "BASELINE",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "warlock.soft-cc.banish",
    name: "Banish",
    spellIds: [710],
    classSlug: "warlock",
    roles: DPS,
    category: "SOFT_CC",
    availability: "BASELINE",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "warlock.group-utility.demonic-gateway",
    name: "Demonic Gateway",
    spellIds: [111771],
    aliases: [113942],
    classSlug: "warlock",
    roles: DPS,
    category: "GROUP_UTILITY",
    availability: "BASELINE",
    cooldownSeconds: 10,
    notes:
      "111771 = Gateway placement cast (credit). 113942 = gateway traversal debuff — evidence-only alias, not a second placement.",
  }),
  rule({
    canonicalKey: "warlock.movement.demonic-circle",
    name: "Demonic Circle",
    spellIds: [48018],
    aliases: [48020],
    classSlug: "warlock",
    specSlugs: [...WARLOCK_SPECS],
    roles: DPS,
    category: "MOVEMENT_UTILITY",
    availability: "TALENT",
    cooldownSeconds: 30,
    notes:
      "48018 = Summon/placement; 48020 = Teleport. Personal movement Utility for Warlock — not Demonic Gateway.",
  }),
  rule({
    canonicalKey: "warlock.caster-control.curse-of-tongues",
    name: "Curse of Tongues",
    spellIds: [1714],
    classSlug: "warlock",
    specSlugs: [...WARLOCK_SPECS],
    roles: DPS,
    category: "SOFT_CC",
    availability: "BASELINE",
    cooldownSeconds: 0,
    notes: "Caster-control debuff; scored under Utility V2 caster-control domain, not generic CC.",
  }),
  rule({
    canonicalKey: "warlock.caster-control.blight-of-tongues",
    name: "Blight of Tongues",
    spellIds: [1271802],
    classSlug: "warlock",
    specSlugs: [...WARLOCK_SPECS],
    roles: DPS,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 0,
    notes: "Affliction-style tongues variant; Utility V2 caster-control domain.",
  }),
  rule({
    canonicalKey: "warlock.dispel.singe-magic",
    name: "Singe Magic",
    spellIds: [89808],
    aliases: [132411, 1276623],
    classSlug: "warlock",
    roles: DPS,
    category: "DISPEL",
    sourceOwnership: "PET",
    availability: "PET_DEPENDENT",
    cooldownSeconds: 15,
    provenance: {
      source: "REPOSITORY_FIXTURE",
      sourceId: "imp",
      verifiedAt: "2026-08-05",
      gameVersion: "12.0.0",
      notes:
        "132411 = Dispels stream activation; 1276623 = Singe Magic buff aura on Buffs (1WKcCz2BnAQmbhfq:1).",
    },
    notes: "Imp defensive dispel attributed to player.",
  }),
  rule({
    canonicalKey: "warlock.battle-rez.soulstone",
    name: "Soulstone",
    spellIds: [20707],
    classSlug: "warlock",
    roles: DPS,
    category: "BATTLE_REZ",
    availability: "BASELINE",
    cooldownSeconds: 600,
    provenance: {
      source: "REPOSITORY_FIXTURE",
      verifiedAt: "2026-08-05",
      gameVersion: "12.0.0",
      notes:
        "Combat resurrection cast 20707 verified on Casts for 1WKcCz2BnAQmbhfq:1 (Wallidrixe → Missmygrip).",
    },
  }),
  rule({
    canonicalKey: "warlock.defensive-minor.dark-pact",
    name: "Dark Pact",
    spellIds: [108416],
    classSlug: "warlock",
    roles: DPS,
    category: "DEFENSIVE_MINOR",
    availability: "TALENT",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "warlock.defensive-major.unending-resolve",
    name: "Unending Resolve",
    spellIds: [104773],
    classSlug: "warlock",
    roles: DPS,
    category: "DEFENSIVE_MAJOR",
    availability: "BASELINE",
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "warlock.self-heal.drain-life",
    name: "Drain Life",
    spellIds: [234153],
    classSlug: "warlock",
    roles: DPS,
    category: "SELF_HEAL",
    availability: "BASELINE",
  }),
  rule({
    canonicalKey: "warlock.soft-cc.howl-of-terror",
    name: "Howl of Terror",
    spellIds: [5484],
    classSlug: "warlock",
    roles: DPS,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 40,
  }),
  rule({
    canonicalKey: "warlock.hard-cc.grimoire-of-sacrifice",
    name: "Grimoire of Sacrifice",
    spellIds: [108503],
    classSlug: "warlock",
    specSlugs: ["affliction", "destruction"],
    roles: DPS,
    category: "GROUP_UTILITY",
    sharedAcrossSpecs: false,
    availability: "CHOICE_NODE",
    supportCertainty: "uncertain",
    notes: "Choice node vs pet; utility relevance is limited — marked uncertain for applicability.",
  }),

  // Performance offensive cooldowns (canonical AbilityRule entries).
    performanceCooldownRule({
      canonicalKey: "warlock.offensive.demonic-tyrant",
      name: "Summon Demonic Tyrant",
      spellIds: [265187],
      activationSpellIds: [265187],
      classSlug: "warlock",
      specSlugs: ["demonology"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 60,
      activationSource: "PLAYER_CAST",
      activationEventTypes: ["begincast", "cast", "applybuff"],
      notes: "Primary Demo offensive cooldown; cast-primary (begincast correlates).",
    }),
    performanceCooldownRule({
      canonicalKey: "warlock.offensive.grimoire-felguard",
      name: "Grimoire: Felguard",
      spellIds: [111898],
      classSlug: "warlock",
      specSlugs: ["demonology"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 120,
    }),
    performanceCooldownRule({
      canonicalKey: "warlock.offensive.nether-portal",
      name: "Nether Portal",
      spellIds: [267217],
      activationBuffIds: [267218],
      classSlug: "warlock",
      specSlugs: ["demonology"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 180,
    }),
    performanceCooldownRule({
      canonicalKey: "warlock.offensive.demonic-strength",
      name: "Demonic Strength",
      spellIds: [267171],
      classSlug: "warlock",
      specSlugs: ["demonology"],
      roles: DPS,
      category: "OFFENSIVE_MINOR",
      availability: "TALENT",
      cooldownSeconds: 60,
    }),
    performanceCooldownRule({
      canonicalKey: "warlock.offensive.guillotine",
      name: "Guillotine",
      spellIds: [386833],
      classSlug: "warlock",
      specSlugs: ["demonology"],
      roles: DPS,
      category: "OFFENSIVE_MINOR",
      availability: "TALENT",
      cooldownSeconds: 45,
    }),
    performanceCooldownRule({
      canonicalKey: "warlock.offensive.summon-darkglare",
      name: "Summon Darkglare",
      spellIds: [205180],
      classSlug: "warlock",
      specSlugs: ["affliction"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 120,
      sourceOwnership: "ANY_OWNED",
    }),
    performanceCooldownRule({
      canonicalKey: "warlock.offensive.phantom-singularity",
      name: "Phantom Singularity",
      spellIds: [205179],
      aliases: [386997],
      classSlug: "warlock",
      specSlugs: ["affliction"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 45,
      notes: "Soul Rot (386997) is the talent replacement path.",
    }),
    performanceCooldownRule({
      canonicalKey: "warlock.offensive.malevolence",
      name: "Malevolence",
      spellIds: [442726],
      classSlug: "warlock",
      specSlugs: ["affliction"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "TALENT",
      cooldownSeconds: 60,
      notes: "Hero-talent era Affliction CD — verify on next Blizzard talent snapshot.",
    }),
    performanceCooldownRule({
      canonicalKey: "warlock.offensive.summon-infernal",
      name: "Summon Infernal",
      spellIds: [1122],
      classSlug: "warlock",
      specSlugs: ["destruction"],
      roles: DPS,
      category: "OFFENSIVE_MAJOR",
      availability: "BASELINE",
      cooldownSeconds: 180,
      sourceOwnership: "ANY_OWNED",
    }),
    performanceCooldownRule({
      canonicalKey: "warlock.offensive.ritual-of-ruin",
      name: "Dimensional Rift",
      spellIds: [387976],
      classSlug: "warlock",
      specSlugs: ["destruction"],
      roles: DPS,
      category: "OFFENSIVE_MINOR",
      availability: "TALENT",
      cooldownSeconds: 45,
      charges: 3,
    }),
];

export const WARLOCK_ALL_SPEC_SLUGS = [...WARLOCK_SPECS];
