import type { AbilityRule } from "../../types.js";
import { ALL_ROLES, DPS, rule } from "../rule.js";

const WARLOCK_SPECS = ["affliction", "demonology", "destruction"] as const;

/**
 * Warlock catalog (all specs). Demonology remains the primary live validation fixture.
 * Spell IDs from repository fixture warlock-demonology-tww-1 plus class-wide expansions.
 */
export const WARLOCK_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "warlock.interrupt.spell-lock",
    name: "Spell Lock",
    spellIds: [19647],
    classSlug: "warlock",
    roles: DPS,
    category: "INTERRUPT",
    sourceOwnership: "PET",
    availability: "PET_DEPENDENT",
    cooldownSeconds: 24,
    requiresSuccessfulTarget: true,
    provenance: {
      source: "REPOSITORY_FIXTURE",
      sourceId: "felhunter",
      verifiedAt: "2026-07-28",
      gameVersion: "12.0.0",
      notes: "Felhunter interrupt; attributed to player.",
    },
  }),
  rule({
    canonicalKey: "warlock.interrupt.axe-toss",
    name: "Axe Toss",
    spellIds: [89766],
    aliases: [347008],
    classSlug: "warlock",
    specSlugs: ["demonology"],
    roles: DPS,
    category: "INTERRUPT",
    sourceOwnership: "PET",
    sharedAcrossSpecs: false,
    availability: "PET_DEPENDENT",
    cooldownSeconds: 30,
    requiresSuccessfulTarget: true,
    provenance: {
      source: "REPOSITORY_FIXTURE",
      sourceId: "felguard",
      verifiedAt: "2026-07-28",
      gameVersion: "12.0.0",
      notes: "Alias 347008 verified on WCL Interrupts stream (Felguard Axe Toss variant).",
    },
  }),
  rule({
    canonicalKey: "warlock.interrupt.optical-blast",
    name: "Optical Blast",
    spellIds: [119910],
    aliases: [115781],
    classSlug: "warlock",
    roles: DPS,
    category: "INTERRUPT",
    sourceOwnership: "PET",
    availability: "PET_DEPENDENT",
    cooldownSeconds: 24,
    requiresSuccessfulTarget: true,
    supportCertainty: "uncertain",
    notes: "Observer / Command Demon interrupt variant; alias retained for WCL cast ID drift.",
  }),
  rule({
    canonicalKey: "warlock.hard-cc.shadowfury",
    name: "Shadowfury",
    spellIds: [30283],
    classSlug: "warlock",
    specSlugs: [...WARLOCK_SPECS],
    roles: DPS,
    category: "HARD_CC",
    availability: "BASELINE",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "warlock.soft-cc.mortal-coil",
    name: "Mortal Coil",
    spellIds: [6789],
    classSlug: "warlock",
    roles: DPS,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 45,
  }),
  rule({
    canonicalKey: "warlock.soft-cc.fear",
    name: "Fear",
    spellIds: [5782],
    classSlug: "warlock",
    roles: DPS,
    category: "SOFT_CC",
    availability: "BASELINE",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "warlock.soft-cc.banish",
    name: "Banish",
    spellIds: [710],
    classSlug: "warlock",
    roles: DPS,
    category: "SOFT_CC",
    availability: "BASELINE",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "warlock.group-utility.demonic-gateway",
    name: "Demonic Gateway",
    spellIds: [111771],
    aliases: [113942],
    classSlug: "warlock",
    roles: DPS,
    category: "GROUP_UTILITY",
    availability: "BASELINE",
    cooldownSeconds: 10,
    notes: "113942 is the gateway traversal debuff observed on WCL Buffs/Debuffs streams.",
  }),
  rule({
    canonicalKey: "warlock.caster-control.curse-of-tongues",
    name: "Curse of Tongues",
    spellIds: [1714],
    classSlug: "warlock",
    specSlugs: [...WARLOCK_SPECS],
    roles: DPS,
    category: "SOFT_CC",
    availability: "BASELINE",
    cooldownSeconds: 0,
    notes: "Caster-control debuff; scored under Utility V2 caster-control domain, not generic CC.",
  }),
  rule({
    canonicalKey: "warlock.caster-control.blight-of-tongues",
    name: "Blight of Tongues",
    spellIds: [1271802],
    classSlug: "warlock",
    specSlugs: [...WARLOCK_SPECS],
    roles: DPS,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 0,
    notes: "Affliction-style tongues variant; Utility V2 caster-control domain.",
  }),
  rule({
    canonicalKey: "warlock.dispel.singe-magic",
    name: "Singe Magic",
    spellIds: [89808],
    aliases: [132411],
    classSlug: "warlock",
    roles: DPS,
    category: "DISPEL",
    sourceOwnership: "PET",
    availability: "PET_DEPENDENT",
    cooldownSeconds: 15,
    provenance: {
      source: "REPOSITORY_FIXTURE",
      sourceId: "imp",
      verifiedAt: "2026-07-29",
      gameVersion: "12.0.0",
      notes: "Alias 132411 verified on WCL Dispels stream (Imp Singe Magic variant).",
    },
    notes: "Imp defensive dispel attributed to player.",
  }),
  rule({
    canonicalKey: "warlock.defensive-minor.dark-pact",
    name: "Dark Pact",
    spellIds: [108416],
    classSlug: "warlock",
    roles: DPS,
    category: "DEFENSIVE_MINOR",
    availability: "TALENT",
    cooldownSeconds: 60,
  }),
  rule({
    canonicalKey: "warlock.defensive-major.unending-resolve",
    name: "Unending Resolve",
    spellIds: [104773],
    classSlug: "warlock",
    roles: DPS,
    category: "DEFENSIVE_MAJOR",
    availability: "BASELINE",
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "warlock.self-heal.drain-life",
    name: "Drain Life",
    spellIds: [234153],
    classSlug: "warlock",
    roles: DPS,
    category: "SELF_HEAL",
    availability: "BASELINE",
  }),
  rule({
    canonicalKey: "warlock.soft-cc.howl-of-terror",
    name: "Howl of Terror",
    spellIds: [5484],
    classSlug: "warlock",
    roles: DPS,
    category: "SOFT_CC",
    availability: "TALENT",
    cooldownSeconds: 40,
  }),
  rule({
    canonicalKey: "warlock.hard-cc.grimoire-of-sacrifice",
    name: "Grimoire of Sacrifice",
    spellIds: [108503],
    classSlug: "warlock",
    specSlugs: ["affliction", "destruction"],
    roles: DPS,
    category: "GROUP_UTILITY",
    sharedAcrossSpecs: false,
    availability: "CHOICE_NODE",
    supportCertainty: "uncertain",
    notes: "Choice node vs pet; utility relevance is limited — marked uncertain for applicability.",
  }),
];

export const WARLOCK_ALL_SPEC_SLUGS = [...WARLOCK_SPECS];
