import type { AbilityRule } from "../../types.js";
import { ALL_ROLES, DPS, TANK, TANK_DPS, rule } from "../rule.js";

/** Warrior survival / utility catalog (Retail M+). */
export const WARRIOR_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "warrior.interrupt.pummel",
    name: "Pummel",
    spellIds: [6552],
    iconName: "ability_warrior_shieldbash",
    classSlug: "warrior",
    roles: ALL_ROLES,
    category: "INTERRUPT",
    cooldownSeconds: 15,
    requiresSuccessfulTarget: true,
  }),
  rule({
    canonicalKey: "warrior.hard-cc.storm-bolt",
    name: "Storm Bolt",
    spellIds: [107570],
    classSlug: "warrior",
    roles: ALL_ROLES,
    category: "HARD_CC",
    availability: "TALENT",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "warrior.soft-cc.intimidating-shout",
    name: "Intimidating Shout",
    spellIds: [5246],
    classSlug: "warrior",
    roles: ALL_ROLES,
    category: "SOFT_CC",
    cooldownSeconds: 90,
  }),
  rule({
    canonicalKey: "warrior.defensive-major.die-by-the-sword",
    name: "Die by the Sword",
    spellIds: [118038],
    classSlug: "warrior",
    specSlugs: ["arms", "fury"],
    roles: DPS,
    category: "DEFENSIVE_MAJOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "warrior.defensive-major.enraged-regeneration",
    name: "Enraged Regeneration",
    spellIds: [184364],
    classSlug: "warrior",
    specSlugs: ["fury"],
    roles: DPS,
    category: "DEFENSIVE_MAJOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 120,
  }),
  rule({
    canonicalKey: "warrior.defensive-major.shield-wall",
    name: "Shield Wall",
    spellIds: [871],
    classSlug: "warrior",
    specSlugs: ["protection"],
    roles: TANK,
    category: "DEFENSIVE_MAJOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 240,
  }),
  rule({
    canonicalKey: "warrior.defensive-major.last-stand",
    name: "Last Stand",
    spellIds: [12975],
    classSlug: "warrior",
    specSlugs: ["protection"],
    roles: TANK,
    category: "DEFENSIVE_MAJOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "warrior.defensive-minor.spell-reflection",
    name: "Spell Reflection",
    spellIds: [23920],
    classSlug: "warrior",
    roles: ALL_ROLES,
    category: "DEFENSIVE_MINOR",
    cooldownSeconds: 25,
  }),
  rule({
    canonicalKey: "warrior.defensive-minor.ignore-pain",
    name: "Ignore Pain",
    spellIds: [190456],
    classSlug: "warrior",
    specSlugs: ["protection"],
    roles: TANK,
    category: "DEFENSIVE_MINOR",
    sharedAcrossSpecs: false,
    cooldownSeconds: 12,
  }),
  rule({
    canonicalKey: "warrior.self-heal.impending-victory",
    name: "Impending Victory",
    spellIds: [202168],
    classSlug: "warrior",
    roles: TANK_DPS,
    category: "SELF_HEAL",
    cooldownSeconds: 25,
  }),
  rule({
    canonicalKey: "warrior.external-defensive.intervene",
    name: "Intervene",
    spellIds: [3411],
    classSlug: "warrior",
    roles: ALL_ROLES,
    category: "EXTERNAL_DEFENSIVE",
    cooldownSeconds: 30,
  }),
  rule({
    canonicalKey: "warrior.group-utility.rallying-cry",
    name: "Rallying Cry",
    spellIds: [97462],
    classSlug: "warrior",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    cooldownSeconds: 180,
  }),
  rule({
    canonicalKey: "warrior.group-utility.demoralizing-shout",
    name: "Demoralizing Shout",
    spellIds: [1160],
    classSlug: "warrior",
    roles: ALL_ROLES,
    category: "GROUP_UTILITY",
    cooldownSeconds: 45,
  }),
  rule({
    canonicalKey: "warrior.immunity.berserker-rage",
    name: "Berserker Rage",
    spellIds: [18499],
    classSlug: "warrior",
    roles: ALL_ROLES,
    category: "IMMUNITY",
    cooldownSeconds: 60,
  }),
];
