import type { Grade } from "@mplus/contracts";

export interface AddonExportEntry {
  region: string;
  realmSlug: string;
  normalizedName: string;
  grade: Grade;
  overallScore: number;
  confidence: number;
}

export interface AddonLuaShard {
  formatVersion: string;
  generatedAt: string;
  region: string;
  seasonSlug: string;
  modelKey: string;
  modelVersion: number;
  checksum: string;
  entries: AddonExportEntry[];
}

function luaEscape(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Builds a Lua table string safe for WoW addon static data (grades only). */
export function renderAddonLua(shard: AddonLuaShard): string {
  const lines: string[] = [
    "-- Generated by @mplus/addon-exporter — do not edit manually",
    `MPlusTrustDB = MPlusTrustDB or {}`,
    `MPlusTrustDB.formatVersion = "${luaEscape(shard.formatVersion)}"`,
    `MPlusTrustDB.generatedAt = "${luaEscape(shard.generatedAt)}"`,
    `MPlusTrustDB.region = "${luaEscape(shard.region)}"`,
    `MPlusTrustDB.seasonSlug = "${luaEscape(shard.seasonSlug)}"`,
    `MPlusTrustDB.modelKey = "${luaEscape(shard.modelKey)}"`,
    `MPlusTrustDB.modelVersion = ${shard.modelVersion}`,
    `MPlusTrustDB.checksum = "${luaEscape(shard.checksum)}"`,
    "MPlusTrustDB.grades = {",
  ];

  for (const entry of shard.entries) {
    const key = `${entry.region}|${entry.realmSlug}|${entry.normalizedName}`.toLowerCase();
    lines.push(
      `  ["${luaEscape(key)}"] = { grade = "${entry.grade}", score = ${Math.round(entry.overallScore)}, confidence = ${entry.confidence.toFixed(2)} },`,
    );
  }

  lines.push("}", "");
  return lines.join("\n");
}

export function lookupGrade(
  shard: AddonLuaShard,
  region: string,
  realmSlug: string,
  name: string,
): { grade: Grade; score: number; confidence: number } | null {
  const key = `${region}|${realmSlug}|${name}`.toLowerCase();
  const entry = shard.entries.find(
    (e) => `${e.region}|${e.realmSlug}|${e.normalizedName}`.toLowerCase() === key,
  );
  if (!entry) return null;
  return { grade: entry.grade, score: Math.round(entry.overallScore), confidence: entry.confidence };
}
