import type { AbilityRule } from "../../types.js";
import { ALL_ROLES, rule, performanceCooldownRule } from "../rule.js";

/**
 * Racials are optional Utility/Performance candidates when `includeRacials` is set.
 * `includeRacials` expands the candidate universe only — race compatibility and/or
 * observed use decide AVAILABLE via resolveAbilityCapability.
 */
export const SHARED_RACIAL_RULES: AbilityRule[] = [
  rule({
    canonicalKey: "shared.racial.stoneform",
    name: "Stoneform",
    spellIds: [20594],
    classSlug: null,
    roles: ALL_ROLES,
    category: "DISPEL",
    availability: "SHARED",
    raceSlugs: ["dwarf"],
    sharedAcrossSpecs: true,
    cooldownSeconds: 120,
    supportCertainty: "uncertain",
    notes:
      "Dwarf racial self-dispel (dispelPurge family). Not movement. Not Dark Iron (Fireblood is separate).",
  }),
  rule({
    canonicalKey: "shared.racial.fireblood",
    name: "Fireblood",
    spellIds: [265221],
    activationBuffIds: [265221],
    classSlug: null,
    roles: ALL_ROLES,
    category: "DISPEL",
    dimensionTags: ["UTILITY_DISPEL", "PERFORMANCE_OFFENSIVE_COOLDOWN"],
    activationEventTypes: ["begincast", "cast", "applybuff"],
    activationSource: "PLAYER_CAST",
    availability: "SHARED",
    raceSlugs: ["dark-iron-dwarf"],
    sharedAcrossSpecs: true,
    cooldownSeconds: 120,
    supportCertainty: "uncertain",
    notes:
      "Dark Iron Dwarf racial — dual-use dispel + offensive secondary. Not Stoneform.",
  }),
  rule({
    canonicalKey: "shared.racial.escape-artist",
    name: "Escape Artist",
    spellIds: [20589],
    classSlug: null,
    roles: ALL_ROLES,
    category: "MOVEMENT_UTILITY",
    availability: "SHARED",
    raceSlugs: ["gnome", "mechagnome"],
    sharedAcrossSpecs: true,
    cooldownSeconds: 60,
    supportCertainty: "uncertain",
    notes: "Gnome racial root/snare break — movement family; race-gated.",
  }),
  rule({
    canonicalKey: "shared.racial.shadowmeld",
    name: "Shadowmeld",
    spellIds: [58984],
    classSlug: null,
    roles: ALL_ROLES,
    category: "DEFENSIVE_MINOR",
    availability: "SHARED",
    raceSlugs: ["night-elf"],
    sharedAcrossSpecs: true,
    cooldownSeconds: 120,
    supportCertainty: "uncertain",
    notes:
      "Night Elf racial only — Survival personal defensive, not a Utility V2 family / not movement. Void Elf uses Spatial Rift.",
  }),
  rule({
    canonicalKey: "shared.racial.spatial-rift",
    name: "Spatial Rift",
    spellIds: [256948],
    aliases: [257040],
    classSlug: null,
    roles: ALL_ROLES,
    category: "MOVEMENT_UTILITY",
    availability: "SHARED",
    raceSlugs: ["void-elf"],
    sharedAcrossSpecs: true,
    cooldownSeconds: 180,
    supportCertainty: "uncertain",
    notes:
      "Void Elf racial mobility (place rift 256948 / traverse 257040). Not Shadowmeld.",
  }),

  // Performance offensive cooldowns (canonical AbilityRule entries).
    performanceCooldownRule({
      canonicalKey: "shared.racial.offensive.blood-fury",
      name: "Blood Fury",
      spellIds: [20572],
      aliases: [33697, 33702],
      activationBuffIds: [20572, 33697, 33702],
      classSlug: null,
      roles: ALL_ROLES,
      category: "OFFENSIVE_MINOR",
      availability: "SHARED",
      raceSlugs: ["orc", "maghar-orc"],
      sharedAcrossSpecs: true,
      cooldownSeconds: 120,
      notes: "Orc racial AP/SP — optional Performance input; race-gated.",
    }),
    performanceCooldownRule({
      canonicalKey: "shared.racial.offensive.berserking",
      name: "Berserking",
      spellIds: [26297],
      activationBuffIds: [26297],
      classSlug: null,
      roles: ALL_ROLES,
      category: "OFFENSIVE_MINOR",
      availability: "SHARED",
      raceSlugs: ["troll", "zandalari-troll"],
      sharedAcrossSpecs: true,
      cooldownSeconds: 180,
      notes: "Troll racial haste — optional Performance input; race-gated.",
    }),
    performanceCooldownRule({
      canonicalKey: "shared.racial.offensive.ancestral-call",
      name: "Ancestral Call",
      spellIds: [274738],
      classSlug: null,
      roles: ALL_ROLES,
      category: "OFFENSIVE_MINOR",
      availability: "SHARED",
      raceSlugs: ["maghar-orc"],
      sharedAcrossSpecs: true,
      cooldownSeconds: 120,
      notes: "Mag'har Orc racial — optional Performance input; race-gated.",
    }),
];
