import type { AbilityCatalog } from "../types.js";
import { withSharedRules } from "./shared.js";

/** Bounded Warlock Demonology catalog for Wave 4 live validation (fixture class). */
export const WARLOCK_DEMONOLOGY_CATALOG: AbilityCatalog = withSharedRules({
  catalogVersion: "warlock-demonology-tww-2",
  classSlug: "warlock",
  specSlug: "demonology",
  supported: true,
  rules: [
    {
      spellIds: [19647],
      classSlug: "warlock",
      specSlugs: ["demonology", "destruction", "affliction"],
      roles: ["DPS"],
      category: "INTERRUPT",
      sourceOwnership: "PET",
      cooldownSeconds: 24,
      petRequirement: "felhunter",
    },
    {
      spellIds: [89766],
      classSlug: "warlock",
      specSlugs: ["demonology"],
      roles: ["DPS"],
      category: "INTERRUPT",
      sourceOwnership: "PET",
      cooldownSeconds: 30,
      petRequirement: "felguard",
    },
    {
      spellIds: [119910],
      classSlug: "warlock",
      specSlugs: ["demonology", "destruction", "affliction"],
      roles: ["DPS"],
      category: "INTERRUPT",
      sourceOwnership: "PET",
      cooldownSeconds: 24,
      petRequirement: "imp",
    },
    {
      spellIds: [30283],
      classSlug: "warlock",
      specSlugs: ["demonology", "destruction", "affliction"],
      roles: ["DPS"],
      category: "HARD_CC",
      sourceOwnership: "PLAYER",
      cooldownSeconds: 60,
      sharedAcrossSpecs: true,
    },
    {
      spellIds: [6789],
      classSlug: "warlock",
      specSlugs: [],
      roles: ["DPS"],
      category: "SOFT_CC",
      sourceOwnership: "PLAYER",
      cooldownSeconds: 45,
    },
    {
      spellIds: [5782, 710],
      classSlug: "warlock",
      specSlugs: [],
      roles: ["DPS"],
      category: "SOFT_CC",
      sourceOwnership: "PLAYER",
      cooldownSeconds: 30,
    },
    {
      spellIds: [111771],
      classSlug: "warlock",
      specSlugs: [],
      roles: ["DPS"],
      category: "MOVEMENT_UTILITY",
      sourceOwnership: "PLAYER",
      cooldownSeconds: 10,
    },
    {
      spellIds: [89808],
      classSlug: "warlock",
      specSlugs: [],
      roles: ["DPS"],
      category: "DISPEL",
      sourceOwnership: "PET",
      cooldownSeconds: 15,
      petRequirement: "imp",
    },
    {
      spellIds: [108416],
      classSlug: "warlock",
      specSlugs: [],
      roles: ["DPS"],
      category: "DEFENSIVE_MAJOR",
      sourceOwnership: "PLAYER",
      cooldownSeconds: 60,
    },
    {
      spellIds: [104773],
      classSlug: "warlock",
      specSlugs: [],
      roles: ["DPS"],
      category: "DEFENSIVE_MAJOR",
      sourceOwnership: "PLAYER",
      cooldownSeconds: 180,
    },
    {
      spellIds: [234153],
      classSlug: "warlock",
      specSlugs: [],
      roles: ["DPS"],
      category: "SELF_HEAL",
      sourceOwnership: "PLAYER",
    },
  ],
});
