import type { AbilityCatalog } from "../ability-types.js";

/** Bounded Wave 4 seed — Warlock Demonology + shared potions. Spell IDs live only here. */
export const SEED_ABILITY_CATALOG: AbilityCatalog = {
  catalogVersion: "ability-catalog-v1-survival-agent23",
  seasonSlug: "season-midnight-s1",
  rules: [
    {
      spellId: 19647,
      classSlug: "warlock",
      specSlugs: ["demonology", "affliction", "destruction"],
      categories: ["interrupt"],
      baseCooldownMs: 24_000,
      petRequirement: "felhunter",
      notes: "Spell Lock (Felhunter)",
    },
    {
      spellId: 119910,
      classSlug: "warlock",
      specSlugs: ["demonology", "affliction", "destruction"],
      categories: ["interrupt"],
      baseCooldownMs: 24_000,
      petRequirement: "felhunter",
      notes: "Command Demon → Spell Lock",
    },
    {
      spellId: 132409,
      classSlug: "warlock",
      specSlugs: ["demonology", "affliction", "destruction"],
      categories: ["interrupt"],
      baseCooldownMs: 24_000,
      petRequirement: "felhunter",
      notes: "Spell Lock (Grimoire of Sacrifice / alternate)",
    },
    {
      spellId: 89766,
      classSlug: "warlock",
      specSlugs: ["demonology", "affliction", "destruction"],
      categories: ["crowd_control"],
      baseCooldownMs: 30_000,
      petRequirement: "observer",
      notes: "Axe Toss",
    },
    {
      spellId: 30283,
      classSlug: "warlock",
      specSlugs: ["demonology", "affliction", "destruction"],
      categories: ["crowd_control"],
      baseCooldownMs: 45_000,
      notes: "Shadowfury",
    },
    {
      spellId: 6789,
      classSlug: "warlock",
      specSlugs: ["demonology", "affliction", "destruction"],
      categories: ["crowd_control"],
      baseCooldownMs: 45_000,
      notes: "Mortal Coil",
    },
    {
      spellId: 710,
      classSlug: "warlock",
      specSlugs: ["demonology", "affliction", "destruction"],
      categories: ["crowd_control"],
      notes: "Banish",
    },
    {
      spellId: 5782,
      classSlug: "warlock",
      specSlugs: ["demonology", "affliction", "destruction"],
      categories: ["crowd_control"],
      notes: "Fear",
    },
    {
      spellId: 111771,
      classSlug: "warlock",
      specSlugs: ["demonology", "affliction", "destruction"],
      categories: ["group_support"],
      baseCooldownMs: 10_000,
      notes: "Demonic Gateway",
    },
    {
      spellId: 104773,
      classSlug: "warlock",
      specSlugs: ["demonology", "affliction", "destruction"],
      categories: ["personal_defensive"],
      baseCooldownMs: 180_000,
      notes: "Unending Resolve",
    },
    {
      spellId: 108416,
      classSlug: "warlock",
      specSlugs: ["demonology", "affliction", "destruction"],
      categories: ["personal_defensive"],
      baseCooldownMs: 60_000,
      notes: "Dark Pact",
    },
    {
      spellId: 234153,
      classSlug: "warlock",
      specSlugs: ["demonology", "affliction", "destruction"],
      categories: ["self_heal"],
      notes: "Drain Life",
    },
    {
      spellId: 6262,
      classSlug: "warlock",
      categories: ["self_heal", "health_potion"],
      notes: "Healthstone",
    },
    {
      spellId: 431416,
      classSlug: "*",
      categories: ["health_potion"],
      notes: "Algari Healing Potion (shared; seed id for validation)",
    },
    {
      spellId: 1236940,
      classSlug: "*",
      categories: ["health_potion"],
      notes: "Seasonal healing potion seed — verify live Midnight item/spell ID",
    },
    {
      spellId: 89808,
      classSlug: "warlock",
      specSlugs: ["demonology", "affliction", "destruction"],
      categories: ["defensive_dispel"],
      petRequirement: "imp",
      notes: "Singe Magic",
    },
    {
      spellId: 119905,
      classSlug: "warlock",
      specSlugs: ["demonology", "affliction", "destruction"],
      categories: ["defensive_dispel"],
      petRequirement: "imp",
      notes: "Command Demon → Singe Magic",
    },
  ],
};
