/**
 * Canonical ExBoss English voice-pack alert list, pinned to an upstream commit.
 * Labels and filenames are copied from EXBOSS-ENG Labels.lua + Sounds.lua.
 * English cues are human-readable names for the M+ Trust Factor builder UI.
 */

export const EXBOSS_ENG_ADDON_DIRECTORY = "EXBOSS-ENG";

export const EXBOSS_VOICE_PACK_PROVENANCE = {
  repository: "https://github.com/aizuon/EXBOSS",
  commitSha: "57c3a78ef17c1b4e2a746e04b7700c8ee77c504b",
  packPath: "EXBOSS-ENG",
  /** Interface line from the pinned EXBOSS-ENG snapshot. Not the generated pack's Retail Interface. */
  tocInterface: "120005,120007",
  alertCount: 185,
} as const;

export interface ExBossVoiceAlert {
  /** 0-based position in the upstream Labels.lua / Sounds.lua tables. */
  index: number;
  /** ExBoss / LSM label string (Chinese in the current English pack). */
  label: string;
  /** Original EXBOSS-ENG Sounds/ filename, including .ogg. */
  filename: string;
  /** Human-readable English description of the cue. */
  englishCue: string;
}

/** [label, original .ogg filename, english cue] in canonical upstream order. */
const ALERT_ROWS = [
  ["准备AOE", "prepare-aoe.ogg", "Prepare AOE"],
  ["准备引线", "prepare-beam.ogg", "Prepare beam"],
  ["准备打断", "prepare-interrupt.ogg", "Prepare interrupt"],
  ["准备拉人", "prepare-pull.ogg", "Prepare to pull"],
  ["准备挡线", "prepare-block-line.ogg", "Prepare to block the line"],
  ["准备接圈", "prepare-soak.ogg", "Prepare to soak"],
  ["准备消层", "prepare-clear-stack.ogg", "Prepare to clear stacks"],
  ["准备点名", "prepare-target.ogg", "Prepare targeted"],
  ["准备踩箭", "prepare-arrow.ogg", "Prepare to soak arrows"],
  ["准备进圈", "prepare-enter-circle.ogg", "Prepare to enter the circle"],
  ["准备连线", "prepare-link.ogg", "Prepare link"],
  ["准备送球", "prepare-ball.ogg", "Prepare to pass the orb"],
  ["准备钩人", "prepare-hook.ogg", "Prepare hook"],
  ["准备集合", "prepare-stack.ogg", "Prepare to stack"],
  ["准备驱散", "prepare-dispel.ogg", "Prepare dispel"],
  ["去撞分身", "hit-clone.ogg", "Hit the clone"],
  ["坦克尖刺", "tank-buster.ogg", "Tank buster"],
  ["快卡视角", "fix-camera.ogg", "Break line of sight"],
  ["快去消水", "clear-water.ogg", "Clear the puddle"],
  ["快找光柱", "find-beacon.ogg", "Find the beacon"],
  ["快踩陷阱", "step-trap.ogg", "Step on the trap"],
  ["54321", "54321.ogg", "Countdown 5-4-3-2-1"],
  ["注意击退", "watch-knockback.ogg", "Watch knockback"],
  ["注意头前", "watch-frontal.ogg", "Watch frontal"],
  ["注意挡球", "block-ball.ogg", "Block the orb"],
  ["注意消球", "clear-ball.ogg", "Clear the orb"],
  ["注意躲避", "watch-dodge.ogg", "Watch dodge"],
  ["点名头前", "target-frontal.ogg", "You are the frontal target"],
  ["点名放水", "target-drop-water.ogg", "Drop the puddle"],
  ["点名消线", "target-clear-line.ogg", "Clear the line"],
  ["躲开头前", "dodge-frontal.ogg", "Dodge the frontal"],
  ["转火小怪", "switch-add.ogg", "Switch to the add"],
  ["转阶段", "phase-change.ogg", "Phase change"],
  ["远离BOSS", "away-boss.ogg", "Move away from the boss"],
  ["靠近分散", "spread-close.ogg", "Spread while close"],
  ["风筝小怪", "kite-add.ogg", "Kite the add"],
  ["Boss狂暴", "boss-enrage.ogg", "Boss enrage"],
  ["Boss易伤", "boss-vuln.ogg", "Boss vulnerability"],
  ["你是白色", "you-white.ogg", "You are white"],
  ["你是黑色", "you-black.ogg", "You are black"],
  ["准备AOE(断条)", "prepare-aoe-break.ogg", "Prepare AOE (break the cast)"],
  ["准备吸球", "prepare-absorb-ball.ogg", "Prepare to soak the orb"],
  ["出去放水", "drop-water.ogg", "Go out and drop the puddle"],
  ["去接小怪", "intercept-add.ogg", "Intercept the add"],
  ["射线点你", "beam-on-you.ogg", "Beam on you"],
  ["小心冲击波", "watch-shockwave.ogg", "Watch shockwave"],
  ["小心击飞", "watch-launch.ogg", "Watch knock-up"],
  ["强化奶骑", "empower-hpal.ogg", "Empower Holy Paladin"],
  ["强化惩戒骑", "empower-ret.ogg", "Empower Retribution Paladin"],
  ["强化防骑", "empower-prot.ogg", "Empower Protection Paladin"],
  ["快分散", "spread-now.ogg", "Spread now"],
  ["快打断", "interrupt-now.ogg", "Interrupt now"],
  ["快救人", "rescue-now.ogg", "Rescue now"],
  ["快破盾", "break-shield.ogg", "Break the shield"],
  ["快进罩子", "enter-bubble.ogg", "Enter the bubble"],
  ["拉断连线", "break-link.ogg", "Break the link"],
  ["易伤爆发", "vuln-burst.ogg", "Vulnerability burst"],
  ["注意减伤", "use-defensive.ogg", "Use a defensive"],
  ["注意治疗", "watch-healing.ogg", "Watch healing"],
  ["特殊技能", "special-mechanic.ogg", "Special mechanic"],
  ["转火大怪", "switch-boss.ogg", "Switch to the big add"],
  ["远离大怪", "away-add.ogg", "Move away from the big add"],
  ["集合分摊", "stack-share.ogg", "Stack to share"],
  ["5", "countdown-5.ogg", "Five"],
  ["4", "countdown-4.ogg", "Four"],
  ["3", "countdown-3.ogg", "Three"],
  ["2", "countdown-2.ogg", "Two"],
  ["1", "countdown-1.ogg", "One"],
  ["集合放圈", "stack-drop.ogg", "Stack and drop"],
  ["控断钢条", "cc-cast.ogg", "Crowd-control the cast"],
  ["坦克击退", "tank-knockback.ogg", "Tank knockback"],
  ["召唤小怪", "summon-adds.ogg", "Adds spawning"],
  ["注意点名", "watch-mark.ogg", "Watch the mark"],
  ["注意躲圈", "watch-circle.ogg", "Dodge the circle"],
  ["注意击飞", "watch-launch-hit.ogg", "Watch knock-up hit"],
  ["准备跑圈", "prepare-dance.ogg", "Prepare the dodge dance"],
  ["准备追人", "prepare-fixate.ogg", "Prepare fixate"],
  ["召唤分身", "mirror.ogg", "Clone spawning"],
  ["AOE", "aoe.ogg", "AOE"],
  ["小心脚下", "watch-step.ogg", "Watch your feet"],
  ["连续躲圈", "dodge-repeat.ogg", "Dodge circles repeatedly"],
  ["准备抓人", "prepare-grab.ogg", "Prepare grab"],
  ["控制小怪", "cc-add.ogg", "Crowd-control the add"],
  ["瞄准音符", "aim-note.ogg", "Aim the note"],
  ["唤醒小怪", "wake-adds.ogg", "Adds waking"],
  ["贴边放水", "drop-water-edge.ogg", "Drop the puddle on the edge"],
  ["靠近BOSS", "approach-boss.ogg", "Move to the boss"],
  ["消除连线", "clear-link.ogg", "Clear the link"],
  ["5秒后AOE", "aoe-after-5s.ogg", "AOE in 5 seconds"],
  ["补给协议", "supply-protocol.ogg", "Supply protocol"],
  ["超大AOE", "massive-aoe.ogg", "Massive AOE"],
  ["持续AOE", "aoe-continuous.ogg", "Ongoing AOE"],
  ["打背面", "hit-back.ogg", "Hit the back"],
  ["召唤大怪", "big-adds.ogg", "Big add spawning"],
  ["躲开冲锋", "dodge-charge.ogg", "Dodge the charge"],
  ["躲球", "dodge-orb.ogg", "Dodge the orb"],
  ["躲圈", "dodge-circle.ogg", "Dodge the circle"],
  ["躲射线", "dodge-beam.ogg", "Dodge the beam"],
  ["勾BOSS", "hook-boss.ogg", "Hook the boss"],
  ["获得增益", "get-buff.ogg", "Get the buff"],
  ["集合移动", "move-group.ogg", "Move as a group"],
  ["靠近连线", "approach-link.ogg", "Move to the link"],
  ["快打宝珠", "kill-orb.ogg", "Kill the orb"],
  ["快躲开", "dodge-now.ogg", "Dodge now"],
  ["快跑", "run-now.ogg", "Run now"],
  ["快跑！你被点名", "run-marked.ogg", "Run — you are marked"],
  ["连线点你", "link-on-you.ogg", "Link on you"],
  ["裂隙点你", "rift-on-you.ogg", "Rift on you"],
  ["你被点名", "you-marked.ogg", "You are marked"],
  ["圈住电水", "soak-lightning.ogg", "Soak the lightning"],
  ["停止施法", "stop-cast.ogg", "Stop casting"],
  ["吸收治疗", "heal-absorb.ogg", "Heal absorb"],
  ["小心炸弹", "watch-bomb.ogg", "Watch the bomb"],
  ["小心自爆", "watch-explosion.ogg", "Watch explosion"],
  ["易伤结束", "vuln-over.ogg", "Vulnerability ended"],
  ["音效_Glass", "sound-glass.ogg", "Glass sound"],
  ["音效_Info", "sound-info.ogg", "Info sound"],
  ["音效_叮咚", "sound-ding.ogg", "Ding sound"],
  ["远离人群", "away-group.ogg", "Move away from the group"],
  ["注意躲风", "watch-wind.ogg", "Dodge the wind"],
  ["注意吐息", "watch-breath.ogg", "Watch breath"],
  ["准备易伤", "prepare-vuln.ogg", "Prepare vulnerability"],
  ["目标是你", "target-on-you.ogg", "The target is you"],
  ["吸收盾", "std-absorb.ogg", "Absorb shield"],
  ["注意大怪", "std-add.ogg", "Watch the big add"],
  ["小怪快打", "std-adds.ogg", "Kill the adds"],
  ["注意箭矢", "std-arrow.ogg", "Watch arrows"],
  ["远离", "std-away.ogg", "Move away"],
  ["引导位置", "std-bait.ogg", "Bait the mechanic"],
  ["注意射线", "std-beam.ogg", "Watch the beam"],
  ["黑色", "std-black.ogg", "Black"],
  ["蓝色", "std-blue.ogg", "Blue"],
  ["炸弹", "std-bomb.ogg", "Bomb"],
  ["打破", "std-break.ogg", "Break"],
  ["吐息", "std-breath.ogg", "Breath"],
  ["注意控断", "std-cc.ogg", "Crowd-control now"],
  ["锁链", "std-chain.ogg", "Chains"],
  ["冲锋", "std-charge.ogg", "Charge"],
  ["清除", "std-clear.ogg", "Clear"],
  ["分身", "std-clone.ogg", "Clone"],
  ["诅咒", "std-curse.ogg", "Curse"],
  ["躲地板", "std-dance.ogg", "Dodge the floor"],
  ["疾病", "std-disease.ogg", "Disease"],
  ["驱散", "std-dispel.ogg", "Dispel"],
  ["持续伤害", "std-dot.ogg", "Damage over time"],
  ["放水", "std-drop.ogg", "Drop the puddle"],
  ["激怒", "std-enrage.ogg", "Enrage"],
  ["追人", "std-fixate.ogg", "Fixate"],
  ["抓握", "std-grasp.ogg", "Grasp"],
  ["注意钩人", "std-hook.ogg", "Watch hook"],
  ["进入", "std-in.ogg", "Go in"],
  ["阶段转换", "std-intermission.ogg", "Intermission"],
  ["打断施法", "std-interrupt.ogg", "Interrupt"],
  ["风筝", "std-kite.ogg", "Kite"],
  ["击飞", "std-knock.ogg", "Knock-up"],
  ["跳跃", "std-leap.ogg", "Leap"],
  ["连线", "std-line.ogg", "Link"],
  ["卡视野", "std-los.ogg", "Line of sight"],
  ["点名", "std-mark.ogg", "Marked"],
  ["移动", "std-move.ogg", "Move"],
  ["靠近", "std-near.ogg", "Move close"],
  ["宝珠", "std-orb.ogg", "Orb"],
  ["出出出", "std-out.ogg", "Get out"],
  ["传递", "std-pass.ogg", "Pass"],
  ["刷新", "std-refresh.ogg", "Refresh"],
  ["注意大圈", "std-ring.ogg", "Watch the ring"],
  ["定身", "std-root.ogg", "Root"],
  ["救人", "std-secure.ogg", "Save the player"],
  ["护盾", "std-shield.ogg", "Shield"],
  ["吸收", "std-soak.ogg", "Soak"],
  ["进攻驱散", "std-spellsteal.ogg", "Spellsteal"],
  ["分裂", "std-split.ogg", "Split"],
  ["分散", "std-spread.ogg", "Spread"],
  ["集合站位", "std-stack.ogg", "Stack"],
  ["目标转换", "std-switch.ogg", "Switch target"],
  ["坦克承伤", "std-tank-hit.ogg", "Tank hit"],
  ["坦克击飞", "std-tank-knock.ogg", "Tank knock-up"],
  ["图腾", "std-totem.ogg", "Totem"],
  ["陷阱", "std-trap.ogg", "Trap"],
  ["易伤", "std-vulnerability.ogg", "Vulnerability"],
  ["齐射", "std-volley.ogg", "Volley"],
  ["注意躲波", "std-wave.ogg", "Dodge the wave"],
  ["白色", "std-white.ogg", "White"],
  ["躲风", "std-wind.ogg", "Dodge the wind"],
  ["黄色", "std-yellow.ogg", "Yellow"],
] as const satisfies ReadonlyArray<readonly [string, string, string]>;

export const EXBOSS_VOICE_ALERTS: readonly ExBossVoiceAlert[] = ALERT_ROWS.map(
  ([label, filename, englishCue], index) => ({
    index,
    label,
    filename,
    englishCue,
  }),
);

export function oggStem(filename: string): string {
  return filename.replace(/\.ogg$/i, "");
}

export function customMp3Filename(filename: string): string {
  return `${oggStem(filename)}.mp3`;
}
